### ISSUE TITLE
Fix/re-enable Broken SVG Hamburger Menu (re: #99)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#100]
Our SVG hamburger menu is displaying as invisible (is broken) and is commented out in #99. 
https://github.com/internetarchive/bookreader/pull/99/files#diff-97d22b6210b4955765d770f57c163c30

_Originally posted by @iisa in https://github.com/internetarchive/bookreader/pull/99_

**Comment by cdrini** [comment]
I think the issue is with url encoding; the SVG might have to to be url encoded before it's put in the data line.

**Comment by cdrini** [comment]
This seems to work, but I have less confidence in this than using the patch:
` url('data:image/svg+xml;utf8,%3Csvg%20width%3D%2215px%22%20height%3D%2212px%22%20viewBox%3D%220%200%2015%2012%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%3E%3Cg%20id%3D%22hamburger-svg%22%20stroke%3D%22%23000%22%20stroke-width%3D%221%22%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%20stroke-linecap%3D%22square%22%3E%3Cpath%20d%3D%22M0%2C1%20L14%2C1%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M0%2C6%20L14%2C6%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M0%2C11L14%2C11%22%3E%3C%2Fpath%3E%3C%2Fg%3E%3C%2Fsvg%3E') center/50% 50% no-repeat; `
