### ISSUE TITLE
Pages Appear Blank After Borrowing Book

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#101]
A patron explains

> I'm having trouble reading books that need to be "borrowed" from the Open Library site using the online reader. After choosing "Borrow It" none of the images will load on the screen. I just get a beige rectangle with a broken image icon in the upper left corner. I've been able to read these books in the past, but not lately. I have no problem using the reader with other texts on the archive.org site that don't need to be borrowed.

**Comment by cdrini** [comment]
This is no longer an issue
