### ISSUE TITLE
Group ReadAloud languages by language

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#1055]
Currently the voice options is very long and seemingly ordered at random:
![image](https://user-images.githubusercontent.com/6251786/168185120-df986371-8d3a-4a81-ae7e-aa885a49e2e0.png)

Use `<optgroup>` to display languages in the books language first and at the top. Then have another group for other languages, sorted by language code.

So for example the above would display:

![image](https://user-images.githubusercontent.com/6251786/168186153-7eaefcb9-f8b6-4a0d-a55b-2434dfdcacf3.png)

**Proposal & Constraints**

**Additional Resources**
- Learn more about optgroup: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

**Success Metrics**

> How will you know if this change is successful? What specific metrics are relevant and how do you expect them to change?

**Stakeholders**

> @-tag stakeholders of this feature

**Comment by cdrini** [comment]
@sancodes Would you be interested in tackling a more user-facing change? :)

**Comment by sancodes** [comment]
@cdrini yes I'm willing to. :)

**Comment by cdrini** [comment]
Awesome! This one might be a little trickier, so please let me know if you have any questions! You'll probably need to work somewhere around here: https://github.com/internetarchive/bookreader/blob/5c14e7de8567f739dcf0cc1e04c6c23a0c79272b/src/plugins/tts/plugin.tts.js#L161-L172

**Comment by sancodes** [comment]
@cdrini will do. Will get started on it soon.

**Comment by cdrini** [comment]
Note: Also `this.ttsEngine.bookLanguage` gives the book language (eg `en`)

**Comment by cdrini** [comment]
Hi @sancodes , anything I can help with? :)

**Comment by sancodes** [comment]
@cdrini thank you for checking in. I started taking look at the issue yesterday and my progress so far is minimal. Sorry for the delay. I was confused as to how to group languages together. 

I have ideas, like maybe using ternary inside the map. (but dont really know how)
or, 
I was gonna create a new array of nested object where one element would be languages would be languages with the string present with `en` and other element would be other languages and feed in the object into `voiceMenu`

But to be honest, little lost as how to approach the issue. Any suggestion would be helpful. :)
![Screen Shot 2022-05-19 at 4 42 43 PM](https://user-images.githubusercontent.com/52472550/169421751-4bc30637-7a4c-4fc3-a899-d182b4b756b9.png)

**Comment by cdrini** [comment]
No worries, your second approach seems best! For the first run, let's assume the book is in `en` for now; we can generalize after we get the core code :)

You can do something like this:

```js
const bookLanguages = this.ttsEngine.getVoices().filter(v => v.lang.startsWith('en'));
const otherLanguages = this.ttsEngine.getVoices().filter(v => !v.lang.startsWith('en'));
```

These will be two arrays of voices, and then render each inside an optgroup. You will probably also want to make a helper function, `renderVoiceOption` that renders the `<option >` tag given a voice.

If we wanted something _slightly_ more performant, we could create a helper function called `groupBy`, which given a list of things and a keying function, returns a json object. Something like:

```js
function groupBy(items, keyFn) {...}

groupBy([1,2,3,4,5,6], x => x % 2 == 0 ? 'even' : 'odd') 
// Would return { 'even': [2,4,6], 'odd': [1,3,5] }
```

But since we'll probably never have more than say 100 languages, the performance isn't super important here, so you can use either approach :) 

Does that help?

**Comment by sancodes** [comment]
@cdrini thank you for taking time to explain, it does help solidify my instincts and take away the fear. 

Your explanation does help. I will try tackling with this approach and if stuck will reach out to you.

**Comment by cdrini** [comment]
Awesome, I'm happy to help!
