### ISSUE TITLE
No pages display in WinXP

### ISSUE THREAD

**Issue by AlanHK** [internetarchive/bookreader#1069]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

Using WinXP browser MyPal 29.3.0
No pages display in the reader. all is black.
Tried several books, same result.

Was working until recently.

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

Screen attached, hopefully.

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?
can see pages.
**Context**

> What operating system? What browser type and version?

WinXP browser MyPal 29.3.0
**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by AlanHK** [comment]
Attached screenshot did not show, See it here.
https://i.imgur.com/rPTo37J.png
Seems github does not support my browser either.

**Comment by cdrini** [comment]
Thank you for the report @AlanHK , I'm sorry you're not able to access books :( We had a big core JS change go out on archive.org on Friday. Our team is investigating.

**Comment by cdrini** [comment]
We pushed out a fix to archive.org . Is the book loading for you know?

**Comment by AlanHK** [comment]
Yes! Working again now for all books I tried. Thanks.
