### ISSUE TITLE
text search does not work in Bookreader with WinXP browsers

### ISSUE THREAD

**Issue by AlanHK** [internetarchive/bookreader#1096]
Using "Search inside" I can get "3 results" but none of them are shown, either in their paragraphs below the result, or as page bookmarks 
Using "MyPal" browser 29.3, a Mozilla derivative, on WinXP.
Last version released AFAIK.
See ![screen](https://i.imgur.com/3nrQupA.png)

**Comment by latonv** [comment]
While the fix has been merged in-repo, I don't believe a new BookReader version has been released with it yet (so the fix hasn't gone live yet). I'll re-open this until we can confirm the fix in prod.

**Comment by cdrini** [comment]
Tested on WinXP in browserstack; now works! Thanks @latonv !

**Comment by AlanHK** [comment]
Yes, text search works in MyPal on XP now.
