### ISSUE TITLE
BookReader always 1up when opening into fullscreen mode

### ISSUE THREAD

**Issue by mheiman** [internetarchive/bookreader#1143]
**Description**

When BookReader opens in fullscreen mode (for instance when following a link from OpenLibrary) it seems to always open in 1up, even if the screen width is greater than the 800px cutoff.  Opening books from IA doesn't exhibit this behavior, because they don't start in fullscreen.

**Evidence / Screenshot (if possible)**

Open any book through the OpenLibrary borrow path (e.g. https://openlibrary.org/borrow/ia/dragonravenorday00hent?ref=ol) in a window wider than 800px.

**Expectation**

Books opening in larger browser windows should default to 2up.

**Context**

Verified in newest Firefox and Safari on MacOS and native browsers on iOS.

**Stakeholders**

@cdrini @mheiman

**Comment by joeshajan** [comment]
Hey, @mheiman I'm new to this project. So can you please explain what 1up and 2up mean?

**Comment by mheiman** [comment]
### 1up:
<img width="809" alt="Screenshot 2023-02-07 at 10 26 52 AM" src="https://user-images.githubusercontent.com/886889/217303927-49cab0cf-4f16-454c-ab75-97a847979427.png">

### 2up:
<img width="809" alt="Screenshot 2023-02-07 at 10 27 09 AM" src="https://user-images.githubusercontent.com/886889/217303984-a601bbd2-2e6d-4959-96b7-2dddb9ad8a13.png">

**Comment by Onyx2406** [comment]
I would like to solve this issue. Please assign me! Thanks

**Comment by joeshajan** [comment]
> ### 1up:
> <img alt="Screenshot 2023-02-07 at 10 26 52 AM" width="809" src="https://user-images.githubusercontent.com/886889/217303927-49cab0cf-4f16-454c-ab75-97a847979427.png">
> 
> ### 2up:
> <img alt="Screenshot 2023-02-07 at 10 27 09 AM" width="809" src="https://user-images.githubusercontent.com/886889/217303984-a601bbd2-2e6d-4959-96b7-2dddb9ad8a13.png">

Ok got it. Can you assign this to me? will start working on it then.
