### ISSUE TITLE
Built from source but failed to render.

### ISSUE THREAD

**Issue by FridayCandour** [internetarchive/bookreader#1168]
I built the project from source but it failed to render because jQuery and bookreader failed to load what could be the solution.

**Comment by FridayCandour** [comment]
After building the project from source the PDF rendering is not working. I need help on how to get it working.

**Comment by cdrini** [comment]
Hi @FridayCandour , could please describe the commands you ran to "build from source"? And how you were trying to test the bookreader? That'll help us determine what's going on :)

**Comment by FridayCandour** [comment]
I ran npm run build and npm serve

It works but I got an Error

$ not defined.

**Comment by FridayCandour** [comment]
I'm stuck on this guy's.

How do you have it working locally.

**Comment by cdrini** [comment]
This worked for me:

```
$ npm install

added 5 packages, removed 9 packages, changed 56 packages, and audited 1432 packages in 28s

84 packages are looking for funding
  run `npm fund` for details

17 vulnerabilities (1 low, 4 moderate, 11 high, 1 critical)      

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

$ npm run build
[....]
[build-js] assets by path plugins/*.js 215 KiB 11 assets
[build-js] assets by path *.js 670 KiB
[build-js]   asset BookReader.js 335 KiB [emitted] [minimized] [big] (name: BookReader.js) 2 related assets     
[build-js]   asset ia-bookreader-bundle.js 216 KiB [emitted] [minimized] (name: ia-bookreader-bundle.js) 2 related assets
[build-js]   asset webcomponents-bundle.js 119 KiB [emitted] [minimized] (name: webcomponents-bundle.js) 2 related assets
[build-js] orphan modules 786 KiB [orphan] 172 modules
[build-js] runtime modules 4.08 KiB 9 modules
[build-js] modules by path ./node_modules/core-js/ 296 KiB 259 modules
[build-js] modules by path ./src/ 973 KiB 17 modules
[build-js] modules by path ./node_modules/jquery-ui/ui/ 85.6 KiB 7 modules
[build-js] modules by path ./node_modules/lit/ 47 KiB
[build-js]   ./node_modules/lit/index.js + 3 modules 32.6 KiB [built] [code generated]
[build-js]   ./node_modules/lit/decorators.js + 10 modules 14.3 KiB [built] [code generated]
[build-js] modules by path ./node_modules/jquery.mmenu/dist/ 21 KiB
[build-js]   ./node_modules/jquery.mmenu/dist/js/jquery.mmenu.min.js 15.8 KiB [built] [code generated]
[build-js]   ./node_modules/jquery.mmenu/dist/addons/navbars/jquery.mmenu.navbars.min.js 5.2 KiB [built] [code generated]
[build-js] modules by path ./node_modules/lit-html/*.js 26.5 KiB
[build-js]   ./node_modules/lit-html/lit-html.js 23.1 KiB [built] [code generated]
[build-js]   ./node_modules/lit-html/directive.js 3.46 KiB [built] [code generated]
[build-js] 9 modules
[build-js]
[build-js] WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).     
[build-js] This can impact web performance.
[build-js] Assets:
[build-js]   BookReader.js (335 KiB)
[build-js]
[build-js] WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
[build-js] Entrypoints:
[build-js]   BookReader.js (335 KiB)
[build-js]       BookReader.js
[build-js]
[build-js]
[build-js] WARNING in webpack performance recommendations: 
[build-js] You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
[build-js] For more info visit https://webpack.js.org/guides/code-splitting/
[build-js]
[build-js] webpack 5.51.1 compiled with 3 warnings in 56798 ms
[build-js]
[build-js] asset jquery-3.js 88.5 KiB [emitted] [minimized] (name: jquery-3.js) 1 related asset
[build-js] runtime modules 718 bytes 3 modules
[build-js] cacheable modules 283 KiB
[build-js]   ./src/jquery-wrapper.js 56 bytes [built] [code generated]
[build-js]   ./node_modules/jquery/dist/jquery.js 283 KiB [built] [code generated]
[build-js] webpack 5.51.1 compiled successfully in 26789 ms
[build-js] npm run build-js exited with code 0
[build-css]
[build-css] > @internetarchive/bookreader@5.0.0-57 build-css
[build-css] > npx sass --no-source-map ./src/css/BookReader.scss ./BookReader/BookReader.css
[build-css]
[build-css] npm run build-css exited with code 0
[build-assets]
[build-assets] > @internetarchive/bookreader@5.0.0-57 build-assets
[build-assets] > npx cpx "src/assets/**/*" BookReader && npx svgo -f BookReader/icons && npx svgo -f BookReader/images
[build-assets]
[build-assets] Processing directory 'BookReader/icons':
[build-assets]
[build-assets]
[build-assets] 1up.svg:
[build-assets] Done in 53 ms!
[build-assets] 0.651 KiB - 50.8% = 0.32 KiB
[build-assets]
[build-assets] 2up.svg:
[build-assets] Done in 15 ms!
[build-assets] 0.74 KiB - 47.4% = 0.39 KiB
[build-assets]
[build-assets] advance.svg:
[build-assets] Done in 24 ms!
[build-assets] 1.25 KiB - 61.5% = 0.481 KiB
[build-assets]
[build-assets] close-circle-dark.svg:
[build-assets] Done in 24 ms!
[build-assets] 0.877 KiB - 61.4% = 0.339 KiB
[build-assets]
[build-assets] chevron-right.svg:
[build-assets] Done in 12 ms!
[build-assets] 0.652 KiB - 49.1% = 0.332 KiB
[build-assets]
[build-assets] close-circle.svg:
[build-assets] Done in 8 ms!
[build-assets] 0.876 KiB - 61.3% = 0.339 KiB
[build-assets]
[build-assets] fullscreen.svg:
[build-assets] Done in 15 ms!
[build-assets] 0.585 KiB - 55.3% = 0.262 KiB
[build-assets]
[build-assets] fullscreen_exit.svg:
[build-assets] Done in 15 ms!
[build-assets] 0.612 KiB - 55.7% = 0.271 KiB
[build-assets]
[build-assets] magnify.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.535 KiB - 48% = 0.278 KiB
[build-assets]
[build-assets] play.svg:
[build-assets] Done in 12 ms!
[build-assets] 0.849 KiB - 68.1% = 0.271 KiB
[build-assets]
[build-assets] magnify-plus.svg:
[build-assets] Done in 30 ms!
[build-assets] 1.69 KiB - 42.2% = 0.978 KiB
[build-assets]
[build-assets] read-aloud.svg:
[build-assets] Done in 19 ms!
[build-assets] 1.577 KiB - 65.1% = 0.55 KiB
[build-assets]
[build-assets] playback-speed.svg:
[build-assets] Done in 49 ms!
[build-assets] 2.494 KiB - 79.2% = 0.518 KiB
[build-assets]
[build-assets] review.svg:
[build-assets] Done in 7 ms!
[build-assets] 0.962 KiB - 51.1% = 0.471 KiB
[build-assets]
[build-assets] thumbnails.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.638 KiB - 36.9% = 0.402 KiB
[build-assets]
[build-assets] voice.svg:
[build-assets] Done in 27 ms!
[build-assets] 2.541 KiB - 44.9% = 1.401 KiB
[build-assets]
[build-assets] magnify-minus.svg:
[build-assets] Done in 23 ms!
[build-assets] 1.623 KiB - 43% = 0.926 KiB
[build-assets]
[build-assets] volume-full.svg:
[build-assets] Done in 7 ms!
[build-assets] 0.943 KiB - 58.7% = 0.39 KiB
[build-assets] 
[build-assets] left-arrow.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.482 KiB - 63.6% = 0.176 KiB
[build-assets]
[build-assets] hamburger.svg:
[build-assets] Done in 9 ms!
[build-assets] 0.547 KiB - 55.2% = 0.245 KiB
[build-assets]
[build-assets] pause.svg:
[build-assets] Done in 8 ms!
[build-assets] 0.848 KiB - 65.6% = 0.292 KiB
[build-assets] Processing directory 'BookReader/images':
[build-assets]
[build-assets]
[build-assets] BRicons.svg:
[build-assets] Done in 229 ms!
[build-assets] 38.751 KiB - 25.6% = 28.843 KiB
[build-assets]
[build-assets] icon_book.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.832 KiB - 69.4% = 0.255 KiB
[build-assets]
[build-assets] books_graphic.svg:
[build-assets] Done in 233 ms!
[build-assets] 49.186 KiB - 23.9% = 37.432 KiB
[build-assets]
[build-assets] icon_bookmark.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.642 KiB - 78.2% = 0.14 KiB
[build-assets]
[build-assets] icon_hamburger.svg:
[build-assets] Done in 3 ms!
[build-assets] 1.044 KiB - 74.9% = 0.262 KiB
[build-assets]
[build-assets] icon_info.svg:
[build-assets] Done in 8 ms!
[build-assets] 2.468 KiB - 62% = 0.938 KiB
[build-assets]
[build-assets] icon_one_page.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.578 KiB - 56.1% = 0.254 KiB
[build-assets]
[build-assets] icon_play.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.185 KiB - 30.7% = 0.128 KiB
[build-assets] 
[build-assets] icon_pause.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.159 KiB - 12.3% = 0.14 KiB
[build-assets]
[build-assets] icon_playback-rate.svg:
[build-assets] Done in 10 ms!
[build-assets] 1.242 KiB - 64.1% = 0.446 KiB
[build-assets]
[build-assets] icon_share.svg:
[build-assets] Done in 8 ms!
[build-assets] 1.175 KiB - 59.3% = 0.479 KiB
[build-assets]
[build-assets] icon_search_button.svg:
[build-assets] Done in 19 ms!
[build-assets] 2.3 KiB - 59.2% = 0.938 KiB
[build-assets]
[build-assets] icon_skip-back.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.754 KiB - 55.1% = 0.339 KiB
[build-assets]
[build-assets] icon_speaker.svg:
[build-assets] Done in 3 ms!
[build-assets] 1.397 KiB - 78.1% = 0.306 KiB
[build-assets]
[build-assets] icon_skip-ahead.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.341 KiB - 27.8% = 0.246 KiB
[build-assets]
[build-assets] icon_gear.svg:
[build-assets] Done in 38 ms!
[build-assets] 11.023 KiB - 62% = 4.191 KiB
[build-assets]
[build-assets] icon_thumbnails.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.946 KiB - 53.7% = 0.438 KiB
[build-assets]
[build-assets] icon_speaker_open.svg:
[build-assets] Done in 9 ms!
[build-assets] 1.582 KiB - 63.9% = 0.571 KiB
[build-assets] 
[build-assets] marker_chap-on.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.937 KiB - 67.8% = 0.302 KiB
[build-assets]
[build-assets] icon_two_pages.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.661 KiB - 56.9% = 0.285 KiB
[build-assets]
[build-assets] marker_srch-on.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.927 KiB - 68.1% = 0.296 KiB
[build-assets]
[build-assets] icon_home.svg:
[build-assets] Done in 12 ms!
[build-assets] 2.948 KiB - 70.6% = 0.867 KiB
[build-assets]
[build-assets] marker_chap-off.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.937 KiB - 67.8% = 0.302 KiB
[build-assets]
[build-assets] icon_toc.svg:
[build-assets] Done in 21 ms!
[build-assets] 3.041 KiB - 50.3% = 1.512 KiB
[build-assets] npm run build-assets exited with code 0


$ npm run serve
...
```

Then going to http://localhost:8000/BookReaderDemo/demo-internetarchive.html?ocaid=theworksofplato01platiala shows a book. Is this working for you? Are you doing anything different in these steps?

**Comment by FridayCandour** [comment]
here's the issue i hope you will understand this  because i have followed your step and yet pdf is not rendering.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>$ npm install

up to date, audited 1439 packages in 42s

82 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (6 moderate, 26 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>$  npm run build

> @internetarchive/bookreader@5.0.0-55 build
> npm run clean && npx concurrently --group npm:build-js npm:build-css npm:build-assets


> @internetarchive/bookreader@5.0.0-55 clean
> rm -r BookReader/ || true

[build-js] 
[build-js] > @internetarchive/bookreader@5.0.0-55 build-js
[build-js] > npx webpack
[build-js] 
[build-js] node:internal/crypto/hash:71
[build-js]   this[kHandle] = new _Hash(algorithm, xofLen);
[build-js]                   ^
[build-js] 
[build-js] Error: error:0308010C:digital envelope routines::unsupported
[build-js]     at new Hash (node:internal/crypto/hash:71:19)
[build-js]     at Object.createHash (node:crypto:133:10)
[build-js]     at BulkUpdateDecorator.hashFactory (/node_modules/webpack/lib/util/createHash.js:145:18)
[build-js]     at BulkUpdateDecorator.update (/node_modules/webpack/lib/util/createHash.js:46:50)
[build-js]     at OriginalSource.updateHash (/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
[build-js]     at NormalModule._initBuildHash (/node_modules/webpack/lib/NormalModule.js:888:17)
[build-js]     at handleParseResult (/node_modules/webpack/lib/NormalModule.js:954:10)
[build-js]     at /node_modules/webpack/lib/NormalModule.js:1048:4
[build-js]     at processResult (/node_modules/webpack/lib/NormalModule.js:763:11)
[build-js]     at /node_modules/webpack/lib/NormalModule.js:827:5 {
[build-js]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[build-js]   library: 'digital envelope routines',
[build-js]   reason: 'unsupported',
[build-js]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[build-js] }
[build-js] 
[build-js] Node.js v18.14.0
[build-js] npm run build-js exited with code 1
[build-css] 
[build-css] > @internetarchive/bookreader@5.0.0-55 build-css
[build-css] > npx sass --no-source-map ./src/css/BookReader.scss ./BookReader/BookReader.css
[build-css] 
[build-css] npm run build-css exited with code 0
[build-assets] 
[build-assets] > @internetarchive/bookreader@5.0.0-55 build-assets
[build-assets] > npx cpx "src/assets/**/*" BookReader && npx svgo -f BookReader/icons && npx svgo -f BookReader/images
[build-assets] 
[build-assets] Processing directory 'BookReader/icons':
[build-assets] 
[build-assets] 
[build-assets] 1up.svg:
[build-assets] Done in 26 ms!
[build-assets] 0.651 KiB - 50.8% = 0.32 KiB
[build-assets] 
[build-assets] 2up.svg:
[build-assets] Done in 6 ms!
[build-assets] 0.74 KiB - 47.4% = 0.39 KiB
[build-assets] 
[build-assets] chevron-right.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.652 KiB - 49.1% = 0.332 KiB
[build-assets] 
[build-assets] close-circle-dark.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.877 KiB - 61.4% = 0.339 KiB
[build-assets] 
[build-assets] advance.svg:
[build-assets] Done in 9 ms!
[build-assets] 1.25 KiB - 61.5% = 0.481 KiB
[build-assets] 
[build-assets] close-circle.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.876 KiB - 61.3% = 0.339 KiB
[build-assets] 
[build-assets] fullscreen.svg:
[build-assets] Done in 13 ms!
[build-assets] 0.585 KiB - 55.3% = 0.262 KiB
[build-assets] 
[build-assets] fullscreen_exit.svg:
[build-assets] Done in 14 ms!
[build-assets] 0.612 KiB - 55.7% = 0.271 KiB
[build-assets] 
[build-assets] hamburger.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.547 KiB - 55.2% = 0.245 KiB
[build-assets] 
[build-assets] left-arrow.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.482 KiB - 63.6% = 0.176 KiB
[build-assets] 
[build-assets] magnify-minus.svg:
[build-assets] Done in 7 ms!
[build-assets] 1.623 KiB - 43% = 0.926 KiB
[build-assets] 
[build-assets] magnify-plus.svg:
[build-assets] Done in 8 ms!
[build-assets] 1.69 KiB - 42.2% = 0.978 KiB
[build-assets] 
[build-assets] magnify.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.535 KiB - 48% = 0.278 KiB
[build-assets] 
[build-assets] pause.svg:
[build-assets] Done in 6 ms!
[build-assets] 0.848 KiB - 65.6% = 0.292 KiB
[build-assets] 
[build-assets] play.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.849 KiB - 68.1% = 0.271 KiB
[build-assets] 
[build-assets] playback-speed.svg:
[build-assets] Done in 14 ms!
[build-assets] 2.494 KiB - 79.2% = 0.518 KiB
[build-assets] 
[build-assets] read-aloud.svg:
[build-assets] Done in 11 ms!
[build-assets] 1.577 KiB - 65.1% = 0.55 KiB
[build-assets] 
[build-assets] review.svg:
[build-assets] Done in 5 ms!
[build-assets] 0.962 KiB - 51.1% = 0.471 KiB
[build-assets] 
[build-assets] thumbnails.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.638 KiB - 36.9% = 0.402 KiB
[build-assets] 
[build-assets] voice.svg:
[build-assets] Done in 13 ms!
[build-assets] 2.541 KiB - 44.9% = 1.401 KiB
[build-assets] 
[build-assets] volume-full.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.943 KiB - 58.7% = 0.39 KiB
[build-assets] Processing directory 'BookReader/images':
[build-assets] 
[build-assets] 
[build-assets] BRicons.svg:
[build-assets] Done in 169 ms!
[build-assets] 38.751 KiB - 25.6% = 28.843 KiB
[build-assets] 
[build-assets] books_graphic.svg:
[build-assets] Done in 283 ms!
[build-assets] 49.186 KiB - 23.9% = 37.432 KiB
[build-assets] 
[build-assets] icon_bookmark.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.642 KiB - 78.2% = 0.14 KiB
[build-assets] 
[build-assets] icon_gear.svg:
[build-assets] Done in 25 ms!
[build-assets] 11.023 KiB - 62% = 4.191 KiB
[build-assets] 
[build-assets] icon_hamburger.svg:
[build-assets] Done in 3 ms!
[build-assets] 1.044 KiB - 74.9% = 0.262 KiB
[build-assets] 
[build-assets] icon_home.svg:
[build-assets] Done in 10 ms!
[build-assets] 2.948 KiB - 70.6% = 0.867 KiB
[build-assets] 
[build-assets] icon_info.svg:
[build-assets] Done in 6 ms!
[build-assets] 2.468 KiB - 62% = 0.938 KiB
[build-assets] 
[build-assets] icon_one_page.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.578 KiB - 56.1% = 0.254 KiB
[build-assets] 
[build-assets] icon_playback-rate.svg:
[build-assets] Done in 79 ms!
[build-assets] 1.242 KiB - 64.1% = 0.446 KiB
[build-assets] 
[build-assets] icon_search_button.svg:
[build-assets] Done in 5 ms!
[build-assets] 2.3 KiB - 59.2% = 0.938 KiB
[build-assets] 
[build-assets] icon_share.svg:
[build-assets] Done in 2 ms!
[build-assets] 1.175 KiB - 59.3% = 0.479 KiB
[build-assets] 
[build-assets] icon_skip-ahead.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.341 KiB - 27.8% = 0.246 KiB
[build-assets] 
[build-assets] icon_skip-back.svg:
[build-assets] Done in 2 ms!
[build-assets] 0.754 KiB - 55.1% = 0.339 KiB
[build-assets] 
[build-assets] icon_pause.svg:
[build-assets] Done in 1 ms!
[build-assets] 0.159 KiB - 12.3% = 0.14 KiB
[build-assets] 
[build-assets] icon_play.svg:
[build-assets] Done in 1 ms!
[build-assets] 0.185 KiB - 30.7% = 0.128 KiB
[build-assets] 
[build-assets] icon_book.svg:
[build-assets] Done in 4 ms!
[build-assets] 0.832 KiB - 69.4% = 0.255 KiB
[build-assets] 
[build-assets] icon_speaker_open.svg:
[build-assets] Done in 15 ms!
[build-assets] 1.582 KiB - 63.9% = 0.571 KiB
[build-assets] 
[build-assets] icon_speaker.svg:
[build-assets] Done in 6 ms!
[build-assets] 1.397 KiB - 78.1% = 0.306 KiB
[build-assets] 
[build-assets] icon_two_pages.svg:
[build-assets] Done in 7 ms!
[build-assets] 0.661 KiB - 56.9% = 0.285 KiB
[build-assets] 
[build-assets] marker_chap-off.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.937 KiB - 67.8% = 0.302 KiB
[build-assets] 
[build-assets] marker_srch-on.svg:
[build-assets] Done in 3 ms!
[build-assets] 0.927 KiB - 68.1% = 0.296 KiB
[build-assets] 
[build-assets] marker_chap-on.svg:
[build-assets] Done in 13 ms!
[build-assets] 0.937 KiB - 67.8% = 0.302 KiB
[build-assets] 
[build-assets] icon_thumbnails.svg:
[build-assets] Done in 7 ms!
[build-assets] 0.946 KiB - 53.7% = 0.438 KiB
[build-assets] 
[build-assets] icon_toc.svg:
[build-assets] Done in 35 ms!
[build-assets] 3.041 KiB - 50.3% = 1.512 KiB
[build-assets] npm run build-assets exited with code 0
friday@uiedbook ~/s/docviewer (master) [1]> npm run serve

> @internetarchive/bookreader@5.0.0-55 serve
> npx http-server . --port 8000

Starting up http-server, serving .

http-server version: 14.1.1

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8000
  http://192.168.99.177:8000
Hit CTRL-C to stop the server

[2023-04-13T02:52:03.437Z]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
(node:5883) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2023-04-13T02:52:05.347Z]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
[2023-04-13T02:52:06.251Z]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
[2023-04-13T02:52:08.050Z]  "GET /BookReader/webcomponents-bundle.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
[2023-04-13T02:52:08.053Z]  "GET /BookReader/webcomponents-bundle.js" Error (404): "Not found"
[2023-04-13T02:52:08.062Z]  "GET /BookReader/jquery-3.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
[2023-04-13T02:52:08.075Z]  "GET /BookReader/jquery-3.js" Error (404): "Not found"
[2023-04-13T02:52:08.097Z]  "GET /BookReader/BookReader.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
[2023-04-13T02:52:08.107Z]  "GET /BookReader/BookReader.js" Error (404): "Not found"

**Comment by FridayCandour** [comment]
problem solved sometime ago

here's the problem in the above error log:

[build-js] > @internetarchive/bookreader@5.0.0-55 build-js
[build-js] > npx webpack
[build-js]
[build-js] node:internal/crypto/hash:71
[build-js] this[kHandle] = new _Hash(algorithm, xofLen);
[build-js] ^

what is the cause? 

the project can only be compiled with older versions of node as newer versions of node have no openssl compartiblity hence the above error during webpack build fails.

solution to this? 

dependencies for this project needs to be updated

but theres an option --all-openssl when running the build command to get it to work in compartibilty mode.

thanks.
