### ISSUE TITLE
Design Read Aloud UI Options

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#118]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

1) Right now there is not a way to pause and play audio bookreader -- it restarts from the beginning of the page after you stop
2) There's no UI to change the speed of playback
3) There's no way to seek on the page (e.g. forward or backward a paragraph or page)
4) There's no way to select a voice

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?

A richer experience which treats audio reading as a first class experience:
https://archive.org/~mek/audioreader/index.html?ocaid=adventuresofbobw00burg&page=10

This starts with a design
**Stakeholders**

> @-tag any stakeholders of this bug
@bfalling @mc2 @jbuckner

**Comment by cdrini** [comment]
Marking this as done; the roadmap document is the design, and we have mockups from Jim.
