### ISSUE TITLE
Allow search API url to include port and to use http vs https

### ISSUE THREAD

**Issue by UcDust** [internetarchive/bookreader#1188]
Would it be possible to allow the search url to include a port, and to use http instead of forcing https? Perhaps as properties in the `overrides` param that is passed in. 

Specifically here-
https://github.com/internetarchive/bookreader/blob/f3357ecdd72b7cf7209ae39fe3e21980837c3d1c/src/plugins/search/plugin.search.js#L172

**Comment by AbdullahDaGoat** [comment]
Wouldnt that in a security be sense be less secure, it shouldnt change anything tho

**Comment by UcDust** [comment]
We're running a cluster of docker services behind a proxy, so some of those services don't have ssl certificates. I think it could also be useful for local development to have the option.
