### ISSUE TITLE
When no PPI present, ignore initial zoom real-word max

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#1189]
Currently, mode 2up will render the book at a zoom level so that it fits the screen, _but_ so that it is not larger than the physical real-world size of the book on the user's display. Some books do not have PPI information available. In this case there should be no real-world max.

**Comment by mheiman** [comment]
I was just going to create an issue, but I think it's this same bug.  Is this why https://archive.org/details/phantomfuture01merr/page/n11/mode/2up?ref=ol&view=theater

<img width="1993" alt="Screenshot 2023-05-11 at 10 06 05 AM" src="https://github.com/internetarchive/bookreader/assets/886889/c671b6d2-6268-47ec-b90d-13fe0ca64051">

doesn't look like https://www-isa4.archive.org/details/phantomfuture01merr/page/n11/mode/2up?ref=ol&view=theater (still running the old 2up code)?

<img width="1991" alt="Screenshot 2023-05-11 at 10 07 23 AM" src="https://github.com/internetarchive/bookreader/assets/886889/372e70e3-b6e9-4c39-8f5c-bce829d7ee34">
