### ISSUE TITLE
Convert QUnit Tests to Jest

### ISSUE THREAD

**Issue by jbuckner** [internetarchive/bookreader#120]
**Context**

> We currently have several unit tests in `qunit`, but they are not easily testable in CI testing. We are now using `jest` to run tests so let's convert the `qunit` tests to `jest` tests.

**Success Metrics**

> Our current `qunit` tests gets moved to `jest` and remove the `qunit` versions. 

**NOTE:** There are some tests in `qunit` that may not to be able to be run in `jest` so we may not be able to convert all of them, but let's convert what we can.

**Stakeholders**

> @jbuckner @mc2

**Comment by cdrini** [comment]
This was done by @Pyrojet99 a while ago.
