### ISSUE TITLE
1up default for mobile and 2up for desktop

### ISSUE THREAD

**Issue by teresaejunior** [internetarchive/bookreader#122]
Perhaps when opening from a /stream/ URL, the reader should detect either device type, or screen size, and set 1up/2up accordingly?

2up is not very user-friendly, at least for my device: 

![2up](https://i.imgur.com/qPSuxpe.jpg)

![2up](https://i.imgur.com/GAUOLGm.jpg)

1up specified:

![1up](https://i.imgur.com/aAzBgkC.jpg)

**Comment by iamshubh** [comment]
I will work on this

> Perhaps when opening from a /stream/ URL, the reader should detect either device type, or screen size, and set 1up/2up accordingly?
> 
> 2up is not very user-friendly, at least for my device:
> 
> ![2up](https://camo.githubusercontent.com/f5d1e8744c04c4ccd4f63b566d14c52c87915ccf/68747470733a2f2f692e696d6775722e636f6d2f715053757870652e6a7067)
> 
> ![2up](https://camo.githubusercontent.com/fc6d81fc9b473010ddfee03a93ad15b0d6dcef57/68747470733a2f2f692e696d6775722e636f6d2f4741554f4c476d2e6a7067)
> 
> 1up specified:
> 
> ![1up](https://camo.githubusercontent.com/05aeb8cd89edd47603d9fb1c47730a61f2c08d3f/68747470733a2f2f692e696d6775722e636f6d2f61417a42676b432e6a7067)

**Comment by iamshubh** [comment]
@teresaejunior could you assign it to me!

**Comment by teresaejunior** [comment]
@iamshubh I can't, only someone from the team can do that, see https://stackoverflow.com/q/26752902

There is no one else working on this, though, I believe.

**Comment by tfmorris** [comment]
The poor choice of defaults is exacerbated by the fact that the 1-up toggle is completely hidden in the Settings dialog. I've created #257 to address that (and more importantly, zoom).

**Comment by teresaejunior** [comment]
Seems fixed.
