### ISSUE TITLE
Custom some elements / make project locally

### ISSUE THREAD

**Issue by dhpnli** [internetarchive/bookreader#1278]
**Description**
Trying to custom some element via options.js and / or make the project locally so can be changed and take effect after the changes

Some element like navbar, logo etc. can be changed but it's doesn't happened in both way.

We need to change some elements not in options.js so I want to know how to make some files "locally" and not be taken from 3rd party like internetarchive...

How can we do it?  

**Context**

Chrome, IE, edge the same behavior

Thanks ahead,
David.

**Comment by cdrini** [comment]
Hi @dhpnli .

If you want to change more core BookReader code, edit the code and then run `npm run build`. Then where you are using BookReader, import _all_ the files from your local copy. That should let you see your changes.

Can I have a bit more info about what you are trying to change? We can also add options for the things you want to configure :+1:

**Comment by dhpnli** [comment]
Hi @cdrini and thanks a lot for the response...

OK i'll try, the build is failing so I'll work on it and try to see changes effect.

The import should be from BookReader file or webpack.config? (I'm pretty new with UI (more BE guy) so sorry)
Because I saw there is 2 'imports' for different files so not sure.

And the changes (for now) we want to do is pretty much in menu (like disappear  'share this book' button and etc.)
Or to disappear the first default file in other modes beside 'two pages' because it's seems ireavevant and looks not pretty in other modes.

Thanks again,
BR...
