### ISSUE TITLE
Unable to run css files in Development/Local server.

### ISSUE THREAD

**Issue by Sulochan-khadka** [internetarchive/bookreader#1286]
**Description**

While running npm I and then after running the command npm run serve-dev , the server starts at localhost:8000 but the landing page does not appear as it probably should.

**Evidence / Screenshot (if
 possible)**

<img width="1311" alt="Screenshot 2023-12-04 at 8 42 12 PM" src="https://github.com/internetarchive/bookreader/assets/122200551/19882a03-6853-4486-9576-881e0fcade35">

**Expectation**

<img width="1308" alt="Screenshot 2023-12-04 at 8 51 41 PM" src="https://github.com/internetarchive/bookreader/assets/122200551/e6284675-9827-4ee8-8e2e-77244aff5ad4">

**Context**

MacOs M1 chip

**Comment by cdrini** [comment]
This is the correct landing page for the bookreader application. You are expecting openlibrary.org , that is a separate repository. Check out https://github.com/internetarchive/openlibrary
