### ISSUE TITLE
How to use TTS locally.

### ISSUE THREAD

**Issue by ivan20203** [internetarchive/bookreader#1313]
I just want to ask the specifics on how to configure TTS locally?

I have been able to get the images to work, by changing the uri in the BookReaderJSSimple.js ,         

`        uri: '//archive.org/download/BookReader/img/page002.jpg' },`

But how would i make TTS work?

I assume we need to use OCR to get the words and their position. 

But lets say i use Archive OCR tools : https://github.com/internetarchive/archive-ocr-tools

Which would give me an OCR file of some sort. 

How would i use this file to allow TTS reading locally?

**Comment by dhpnli** [comment]
Hi @ivan20203 where is the answer? How do you managed to make tts to work?

**Comment by dhpnli** [comment]
Hi @cdrini 
Maybe you can help here? How can I manage to "aligned" tts feature to work with our books?

Thanks ahead

**Comment by ivan20203** [comment]
Yeah I could not figure it out. 
Either way i moved on to using Microsoft Edge TTS reader. I just changed the html styling so that it highlights only one line at a time.
