### ISSUE TITLE
iiif plugin, last image of an even number of pages is lost

### ISSUE THREAD

**Issue by glorieux-f** [internetarchive/bookreader#1350]
**Description**

With
https://github.com/internetarchive/bookreader/blob/master/BookReaderDemo/demo-iiif.html
a 2 image manifest shows only the first one
https://glorieux-f.github.io/iiif_tests/bookreader_issue_even-pages.json

**Evidence / Screenshot (if possible)**

Only one image shown in BookReader, impossible to go to the last one.
![image](https://github.com/user-attachments/assets/fc3dcd67-39c6-4675-b65b-ba232634ece8)

Same manifest in Mirador
![image](https://github.com/user-attachments/assets/89d86288-5662-440e-b7bd-d8cc2ec3052e)

**Expectation**

See the last and second image.
![image](https://github.com/user-attachments/assets/7b552913-742b-4f31-a530-8005ca036645)

**Context**

All.

**Proposal & Constraints**

Push last page if any.

https://github.com/internetarchive/bookreader/blob/a9c279c66b9eb0d394304dd3fa88aaef88bdfaa9/src/plugins/plugin.iiif.js#L75
https://github.com/internetarchive/bookreader/blob/a9c279c66b9eb0d394304dd3fa88aaef88bdfaa9/src/plugins/plugin.iiif.js#L115

**Stakeholders**

???

**Comment by glorieux-f** [comment]
Drini Cami, thanks for your fast reaction, even if your services are down right now. Feel free to ask me for more obedience to your coding standarts. We like (love?) your viewer for iiif books, we need some more features (chapters). I will make it work for us, I will make my best to make it work for all.

**Comment by cdrini** [comment]
Thank you for helping improve bookreader! I'm glad you like it 😊 

And please, issue/pr welcome for adding iiif table of contents support. You should just have to update the same file to specify the `table_of_contents` option with the expected fields (see https://github.com/internetarchive/bookreader/blob/0198d87898fcc6d7a06cad9f29f7216ee50dabf6/src/BookReader/options.js#L184 )

**Comment by glorieux-f** [comment]
Yes, I seen it, but I need to see working examples when archive.org will be back. Here is our working site for proofreading of the complete works of “Piaget” (a Swiss psychologist). I’m not sure we are full OK on rights, but we should be one day.
https://oeuvres.unige.ch/piaget/iiif/

**Comment by cdrini** [comment]
Oh very cool! Oh here's a rough example that should work:

```js
table_of_contents: [
    {"level": 1, "label": "Chapter 1", "title": "Through the Looking Glass", "pagenum": "13"},
    {"level": 1, "label": "Chapter 2", "title": "There and Back again", "pagenum": "18"},
    ...
]
```

And add the chapter plugin script to your html. Note that this will look up and try to find the page with the given `pagenum`. If you want to make it explicit, and an `index` parameter to each table of contents entry with the exact index of the page.

See the type definity for `TocEntry`:

https://github.com/internetarchive/bookreader/blob/0198d87898fcc6d7a06cad9f29f7216ee50dabf6/src/plugins/plugin.chapters.js#L84-L100

Thanks for your patience while we work to bring archive.org back up!
