### ISSUE TITLE
Hamburger icon only clickable on lines

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#144]
**Description**
You can only activate the hamburger icon by clicking on the lines; if you click the whitespace between or near the lines, nothing happens.

**Evidence / Screenshot (if possible)**
![bookreader hamburger icon](https://user-images.githubusercontent.com/6251786/65527668-070f2c00-dec1-11e9-9b92-13c4eefc2f6a.gif)

**Expectation**
Clicking anywhere on the containing box should trigger the action.

**Context**
- Windows 10, Firefox 69

**Proposal & Constraints**
- The icon should be in an `<a>` tag with padding; or a button.

**Stakeholders**

@mekarpeles

**Comment by IsAmrish** [comment]
@jbuckner  -- I like to try.

**Comment by jbuckner** [comment]
@IsAmrish Thank you! Go for it!

**Comment by honda0306** [comment]
I'd be happy to take a swing at this if needed as well :)

**Comment by raphaelcleto** [comment]
Hey! I've opened a pull request solving this issue. Could you check it please? #159

**Comment by honda0306** [comment]
> this

Normally I would be happy to, but I'm not a maintainer 😅 From what I can see it looks good!
