### ISSUE TITLE
Add eslint rule comma-dangle: "only-multiline"

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#154]
See https://eslint.org/docs/rules/comma-dangle . Should _only_ apply to the JS in `src/`.

**Comment by Ryuno-Ki** [comment]
Hey @cdrini,
is this open for grabs?

I already forked the repo and got a local version running.
Am I right in assuming, that the option should be `"comma-dangle": ["error", "never"]`?

**Comment by cdrini** [comment]
Hey @Ryuno-Ki ; it looks like @nirmalks has already opened a PR: #155 . But stay tuned! We're going to be opening a number of similar code quality issues around next week. Thanks for your interest!

**Comment by imskr** [comment]
@cdrini Is this still open?

**Comment by iisa** [comment]
Hi @imskr looks like it is still open.  Let's wait a few days to hear back from @nirmalks before you can take over in the fix if you like.

**Comment by surajat17** [comment]
is this issue still open?... if yes i would like to work on it

**Comment by nirmalks** [comment]
Please feel free to take it up

**Comment by surajat17** [comment]
okay thanks i am on it.

**Comment by surajat17** [comment]
@cdrini can you assign it to me?

**Comment by Yashs911** [comment]
@surajat17 are you still working on this issue or I can take it up?

**Comment by Yashs911** [comment]
Hey, @cdrini Can I create a PR for this issue as I guess the previous PR was closed.

**Comment by cdrini** [comment]
:+1: Go for it
