### ISSUE TITLE
Read Aloud breaks up hyphenated words

### ISSUE THREAD

**Issue by dtinth** [internetarchive/bookreader#179]
First, thanks for such an awesome online library. I use Text-to-Speech extensively when reading books from the archive, it helps me concentrate better when reading a book and reduces my eye strain a lot.

**Description**
On digitized books, the hyphenated text has been broken into two words when speaking. For example, the word **negative** has been broken into 2 lines:

An excerpt from the book:

> We can also transform any we consider nega-
> tive

When read aloud, the word "negative" is pronounced as "nega-tive". The "tive" is pronounced like "five" which is incorrect.

**Evidence / Screenshot (if possible)**
It happens on this book a lot (I am loaning it right now, but might also happen with other books). https://archive.org/details/satirmodelfamily00sati

**Expectation**
I expected that hyphenated words are pronounced correctly.

**Context**
macOS Catalina (10.15)
Voice: Samantha
Google Chrome 78.0.3904.87

**Proposal & Constraints**
Automatically delete `- ` (a hyphen followed by a space) when uttering speak. I solved this problem on my side by running this userscript to monkeypatch the browser’s speech synthesis engine:

```js
speechSynthesis.speak = (speak => function(utterance) {
  utterance.text = utterance.text.replace(/- /g, '')
  return speak.call(this, utterance)
})(speechSynthesis.speak)
```

This should not harm the cases where hyphens are expected. For example, the word **life-preserving** has been wrapped into `life- preserving`. Removing the hyphens result in `lifepreserving`, but the TTS engine can pronounce it fine.

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by dtinth** [comment]
Thanks! ❤️

**Comment by cdrini** [comment]
Thank you for opening the issue :) This will be deployed today or tomorrow to production :+1:

**Comment by ishank-dev** [comment]
For some reason, this issue is still persisting in a few of the [contents ](https://archive.org/details/neuro_pattrec/page/n1/mode/2up) from internet archive although it works fine on the books present in open libraries.
