### ISSUE TITLE
Replace Book Title URL with image - is it possible?

### ISSUE THREAD

**Issue by MichaelNZ85** [internetarchive/bookreader#206]
In the top left-hand corner, the `bookTitle` property is displayed as a link to the `bookUrl` address. 

Is it possible to replace this text link with an image, such as a logo, that links to the same URL? If so, how does one go about it?

**Comment by iisa** [comment]
Hi @MichaelNZ85 thanks for checking in. I'm trying to replicate what you saw, can you give a screenshot of what you are seeing?

**Comment by manasivaraiya** [comment]
is the issue solved? if not can i work on it?

**Comment by cdrini** [comment]
Closing since the header bar is no longer a part of the latest BR.
