### ISSUE TITLE
jQuery compatible problem with the search button

### ISSUE THREAD

**Issue by shenzhuxi** [internetarchive/bookreader#24]
Javascript should be made compatible with other libraries than jQuery by adding a small wrapper around your existing code:
(function ($) {
// Original JavaScript code.
})(jQuery);

Here is the patch
http://drupalcode.org/project/fileviewer.git/blob_plain/refs/heads/7.x-1.x:/712462.patch

**Comment by rchrd2** [comment]
Closing this issue since the link no longer works.
