### ISSUE TITLE
End 2 End Test: Read books right to left on archive.org

### ISSUE THREAD

**Issue by iisa** [internetarchive/bookreader#250]
Task: Create a manual end to end test that points to archive.org and tests the Right to Left book reading experience.

- Use base tests provided
- Identify and Create new helper tests that test other cases specific to the Right to Left bookreading experience.

Right to Left (rtl) – BR support rtl books. 
https://archive.org/details/gendaitankashu00meijuoft/
https://archive.org/details/ceilingstarsside00sand

**Comment by SHarma239** [comment]
This seems like a good issue.
