### ISSUE TITLE
End 2 End test: Make Oliver Twist Book pass base test

### ISSUE THREAD

**Issue by iisa** [internetarchive/bookreader#254]
We have a local repo demo that points to the book: Oliver Twist.

When the base tests are applied, they fail.  Create a new test that covers the issue where the test fails.

Task:
- Identify what tests need to be extended in order for it to pass
- Create a test that is particular to the case that is broken.  Make it generic enough for reuse.
- When that edge case has been covered, refactor out the base tests so that we can run this new test instead of the old one that is failing.

**Comment by ishank-dev** [comment]
Can I work on this?
I think I will need some help in knowing the following
1. What type of tests is being referred to here that we have to write?
2. How to go about finding the test case that is broken?

**Comment by iisa** [comment]
HI @ishank-dev thanks a lot.

We essentially want to uncomment this:
`https://github.com/internetarchive/bookreader/blob/master/tests/e2e/base.test.js#L8`
and see the tests pass.

This test is an end-to-end test using TestCafe. See: `https://github.com/internetarchive/bookreader/blob/master/README.md#end-to-end-tests`
---

The fix has a few parts:
1) identify the On Load behavior that makes the Oliver Twist book different from the Plato book.
2) create new tests to make the oliver twist book pass.
3) Refactor current dynamically run tests

I can help you through it if you are interested. =)

**Comment by ishank-dev** [comment]
Thanks, @iisa, I tried running the e2e tests using ``npm run test:e2e`` and surprisingly it passed all 21 test cases. I uncommented the ``demo-ia-olivertwist.html`` as well. <br>Did I go wrong anywhere? 
![Screenshot_20200410_012118](https://user-images.githubusercontent.com/45262592/78935513-87e2ed80-7aca-11ea-88aa-a60bd51ca682.png)

**Comment by iisa** [comment]
hi @ishank-dev thanks for your patience. just did a pass through as well and it seems to have resolved itself.  Yes, please just make a PR with uncommenting this and we will get it in.
