### ISSUE TITLE
Where did BookReaderIA code move to?

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/bookreader#255]
What repo did the code deleted by @rchrd2 in commit f068e4622383c9cf5cb29e2a96b931b0aec01e79 move to?

All Github can seem to find is old forks of the bookreader (ie this) repo.

**Comment by iisa** [comment]
Hi @tfmorris - we actually moved them to the archive.org side.  Is there anything that you are interested in changing, have any questions on?

**Comment by iisa** [comment]
Going to close this. @tfmorris - please reopen if you have any more questions.

**Comment by tfmorris** [comment]
Sorry for the slow reply. I meant to double check the https://github.com/internetarchive repos to see if I'd missed one because I thought I'd checked them all. Can you post the actual URL?

We have an intern who's interested in using the APIs for OpenLibrary. Of course, as an open source project, we also have a strong preference for open source APIs as well. Since they're undocumented, the source code is really the only documentation as well.

**Comment by tfmorris** [comment]
@iisa Am I correct in believing that this code is no longer open source and that the repository that it's been moved to is some private proprietary one?

**Comment by iisa** [comment]
hi @tfmorris! Yes the code is no longer in this repo, but still accessible.  We are a tiny team, and unfortunately, documenting gets lost along the way.  If the work is for the API, I would circle back with @cdrini and @mekarpeles to see what we can do to help them along.

**Comment by rchrd2** [comment]
Some more context: I removed these files, because they were out of date with the in-production files within Archive.org's proprietary codebase.
