### ISSUE TITLE
Allow continuous pinching-zooming

### ISSUE THREAD

**Issue by bfalling** [internetarchive/bookreader#262]
**Context**

The magnification buttons are awkward and only allow zooming in quantized jumps. Panning does not exist. The lack of these common and expected gestures frustrates users and makes reading more difficult and sometimes even impossible.

**Proposal & Constraints**

Improve Zoom so that one can use familiar pinch/zoom gestures to reduce/enlarge book pages. Allow Panning of an image. Both Zooming and Panning should be done with finger gestures and allow for continuous change.

The existing Zoom buttons should be examined to allow for a greater range of Zooming. Sometimes, the reader can no longer Zoom in or out, despite the fact that the image looks like it could support it.

**Acceptance Criteria**

Open any book and be able to pan/zoom pages. The existing Zoom buttons should still work as well.

**Comment by ForgottenProgramme** [comment]
@iisa Can I take it up please?

Also why is this issue marked both 'advanced difficulty'  and 'good first issue' ?

**Comment by AdityaKG-169** [comment]
Hey! I would like to work on this issue.

**Comment by vishwjeet-singh** [comment]
Mam, May I work on this issue?

**Comment by prashant-smart** [comment]
@bfalling  can i work on this issue.
 thankyou

**Comment by cdrini** [comment]
Closed by a few PRs
