### ISSUE TITLE
Share button should provide book deep link as default option

### ISSUE THREAD

**Issue by brierjon** [internetarchive/bookreader#276]
**Description**
The share button for books only provides the url for the book itself, but does not provide deep link sharing. The URL on the other hand does provide the desired parameters to link within the the book to a specific page. The additional parameters to link to specific pages should be made available in the share feature as an option to just share the book or share the specific page. The UI should afford both types of shares, but deep links appear to have been overlooked in the share feature.

1. Open Book
2. Move to any page in the book with arrows
3. Click share button on upper right
4. Compare share URL and Page URL

**Evidence / Screenshot (if possible)**
Page URL while reading shows: https://archive.org/stream/bad0947.0001.001.umich.edu?ref=ol#page/n427/mode/2up

Share URL shows: https://archive.org/stream/bad0947.0001.001.umich.edu?ref=ol

![Screenshot from 2020-04-02 09-33-37](https://user-images.githubusercontent.com/717866/78222556-ba3a8c80-74c5-11ea-8fc1-d4637f50c778.png)
![Screenshot from 2020-04-02 09-33-19](https://user-images.githubusercontent.com/717866/78222565-bc045000-74c5-11ea-8d3f-bed68c7959ae.png)
![Screenshot from 2020-04-02 09-33-02](https://user-images.githubusercontent.com/717866/78222571-be66aa00-74c5-11ea-91ac-16ac73a8a50c.png)

**Expectation**

The share URL should include the parameters for the page being viewed. 

**Context**

Tested on Firefox 74.0 - Pop!_OS 19.10

**Proposal & Constraints**

Adding a checkbox that is checked by default that says something like "share link to this page". By unchecking the box the parameters for the deep link could be removed to only share the book.

This follows more commonly how a share function should work on other sites. You wouldn't just share the blog homepage when sharing from a post page, you would share a particular blog post.

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by ishank-dev** [comment]
I tried this on the local development setup, this seems to work fine. I guess the changes are not deployed yet. The share button opens a window with more options than it does on the archive.org
![Screenshot_20200409_200738](https://user-images.githubusercontent.com/45262592/78907117-e8a80100-7a9d-11ea-9fb2-4632a129d7df.png)
