### ISSUE TITLE
Allow zooming in and out with the +- keys

### ISSUE THREAD

**Issue by rchrd2** [internetarchive/bookreader#282]
**Context**

It would be nice to be able to zoom in and out using the `-` and `+` keys (without holding shift, so technically `-` `=`.

**Proposal & Constraints**

Just trigger zoom in and out with these keys. Same as if you hit the zoom in or out button.

I am browsing some image-heavy magazines/books and this would optimize the experience.

**Comment by ishank-dev** [comment]
You can zoom in and out using Numpad `-` and `+` keys.
