### ISSUE TITLE
Add support for selecting other TTS voices

### ISSUE THREAD

**Issue by ishank-dev** [internetarchive/bookreader#292]
**Context**
The content present on the internet archive is accessed by the audience belonging to different parts of the world. Amongst those readers, many of them are visually impaired who solely rely on audiobooks. But it often becomes difficult to interpret the voice of the narrator in case it gets set to a default voice that is non-native to the reader.
Adding support for choosing the desired native voice that the reader is comfortable with can slightly improve the overall audiobook experience.

**Proposal & Constraints**
It would be great if we could add an option to let users select the audiobook accent of their choice.

**Additional Resources**
Feature Screenshot
![Untitled1](https://user-images.githubusercontent.com/45262592/79765838-c7200280-8344-11ea-913d-17b0db77965b.png)

**Stakeholders**
@cdrini @mekarpeles

**Comment by cdrini** [comment]
Note that the accent of BR is _not_ `British English en-GB`; it chooses the accent based on your browser's language. For e.g., my `navigator.languages` is `[ "en-US", "en", "de-DE" ]`, so it chooses an `en-US` voice if the book is in English.

**Comment by cdrini** [comment]
If there is no accent match, it just chooses the first `en-*` voice on your system.

**Comment by ishank-dev** [comment]
Okay, I have updated the issue description accordingly :+1:
