### ISSUE TITLE
Summary of current forks

### ISSUE THREAD

**Issue by davidzweig2** [internetarchive/bookreader#32]
I would like to contribute to this project, I have some features I would like to add. I'm just wondering which fork to work on, as there seem to be significant amounts of code that have not been merged into the project. aMoniker has added Notes and Annotations support, jgsmith has added a pluggin system. What is the consensus on these modifications, and where is the project heading? Currently I'm working with rrotters fork, as I need to use a recent version of JQuery.

Regards

David

**Comment by cdrini** [comment]
This is the repo to add pull requests to... Quite the delay here 😅
