### ISSUE TITLE
Eslint should also validate the test files

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#331]
Currently eslint is only operating on the src code, but not the tests! The `lint` commands in package.json need to be updated.

### Summary of Requirements
- [ ] All .js files should be validated when running `npm run lint`
- [ ] All the existing violations should be fixed (likely only need to run a `npm run lint:fix`)

**Comment by Kartik1397** [comment]
Hi @cdrini, Can I work on this issue?

**Comment by cdrini** [comment]
Hi @Kartik1397 , yes please! Thank you :)

**Comment by Kartik1397** [comment]
Should I remove these unused variable shown during `npm run lint:fix`?

--------------------------------------------------------------------------------------------

/home/k/bookreader/tests/BookReader/Navbar/Navbar.test.js
  8:29  error  'Navbar' is defined but never used  no-unused-vars

/home/k/bookreader/tests/e2e/autoplay.test.js
  2:8  error  'BookReader' is defined but never used  no-unused-vars
  9:1  error  'fixture' is not defined                no-undef

/home/k/bookreader/tests/plugins/tts/PageChunkIterator.test.js
  2:10  error  'afterEventLoop' is defined but never used  no-unused-vars

**Comment by cdrini** [comment]
Yep! I think they should be safe to remove. Except for fixture.

`fixture` is a global defined by `testcafe`; it looks like we might need to add this plugin to handle that: https://www.npmjs.com/package/eslint-plugin-testcafe . Let me know if you have any questions!
