### ISSUE TITLE
BookReader flipping randomly goes wonky

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#349]
**Description**

Clicking flip forward / backward sometimes causes flipping to go crazy?

**Evidence / Screenshot (if possible)**
![random flipping](https://user-images.githubusercontent.com/6251786/84052438-92ace800-a97e-11ea-821b-172a7cbeaf1b.gif)

Confirmed on:
- https://archive.org/stream/cu31924014450716?ref=ol#page/n45/mode/2up?ref=ol
- https://archive.org/stream/systemsoftwarein0002beck

**Context**

FF 77 @ Win10

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**

@mekarpeles @ishank-dev

**Comment by kristopolous** [comment]
I've been meaning to get more involved in IA stuff, let me see what I can do ... give me a few hours.

**Comment by kristopolous** [comment]
it's a race condition with the url in the locationpolling, if you page in the time window after the animation and before the fragment update it triggers it at 500ms intervals until you get lucky enough to have favorable timing (usually a few times) ... I'll see what I can do about it.

**Comment by mekarpeles** [comment]
Thank you @kristopolous! This is greatly appreciated <3

**Comment by kristopolous** [comment]
the most trivial solution would be to change a few constants around ... the bug will stay in tact but you'll go make it impossible to trigger ... I'll probably submit a few possible patches here and you can choose to accept whatever you'd like.

**Comment by kristopolous** [comment]
it's actually because that link has a querystring in it ... that's what's causing the bug ... pr coming soon.

**Comment by cdrini** [comment]
This re-appeared after the 4.13.1 deploy 😬
