### ISSUE TITLE
demo-advanced doesn't turn pages

### ISSUE THREAD

**Issue by spacejamjim** [internetarchive/bookreader#358]
**Description**

> Followed instructions given in ReadME

**Expectation**

> http://localhost:8000/BookReaderDemo/index.html link to http://localhost:8000/BookReaderDemo/demo-advanced.html -> I should be able to flip pages, but it will not allow me to move past the first page

> Same with demo-plugin-menu-toggle.html

**Context**

> Mac: catalina 10.15.3
> Node: 10.13.0
> Chrome: 83.0.4103.106 (Official Build) (64-bit)

**Comment by Pyrojet99** [comment]
Does not seem to be a configuration-related problem. Probably it has something to do with BookReaderJSAdvanced.js which both demo-advanced.html and demo-plugin-menu-toggle.html share.

**Comment by Pyrojet99** [comment]
Done a little bit of research into that:
- Last working commit   https://github.com/internetarchive/bookreader/commit/797da9273b9e592207d4e1e11e7ecf2213569690

- First commit with this issue https://github.com/internetarchive/bookreader/commit/fdd8c7ebe911a6ec36c7a522d83b925accbb1301

(those two commits are sequential)

**Comment by cdrini** [comment]
It looks like that commit was the v4.12.0 release, so probably one of these commits might have broken it: https://github.com/internetarchive/bookreader/compare/v4.11.1...v4.12.0 . We'll need to build the files to test these commits, because otherwise it'll just use the v4.11.1 build files (where it was working).

**Comment by Pyrojet99** [comment]
Updated:
- Last working commit: f70a9d5321fb129ececbcd1c415cd7d808677573
- First broken commit: af20d90b3267f03bcd90e3179f518dec4e342baa
