### ISSUE TITLE
i can't search in bookreader 

### ISSUE THREAD

**Issue by samirquliyev** [internetarchive/bookreader#36]
i can't search in bookreader on my website.Who can help me?
url:
http://ceferiler.az/bookreader/4%20Risale/4%20risale.html#page/26/mode/2up

**Comment by LeadSongDog** [comment]
I've also been unable to enter a search phrase in bookreader on Safari/iOS7/Ipad

**Comment by rchrd2** [comment]
Closing this since the link does not work. Also we have since added much better mobile support in BookReader v2.
