### ISSUE TITLE
Unable to type "-" or "=" in input fields outside BR

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#371]
To reproduce:
1. Go to https://archive.org/details/completebookofpi00hass
2. Try to type "-" or "=" into the search box at the top of the page

* Expected: Can type them
* Actual: They zoom in/out the BR

## Proposal & Constraints

- Keyboard shortcuts should only work if the event target is not an input box

## Stakeholders

@textfiles

**Comment by JanviMahajan14** [comment]
Hi @cdrini I would like to work on this issue. I am able to run the project locally in my system but not able to understand how I can reproduce this issue ? I checked this http://localhost:8000/BookReaderDemo/demo-internetarchive.html?ocaid=adventuresofoli00dick and I am not able to reproduce this issue. Can you tell me where I can reproduce this issue ?

**Comment by shaneriley** [comment]
@JanviMahajan14 you can open up BookReaderDemo/demo-internetarchive.html, add a form to the bottom of the page like `<form action="" method="get"><textarea rows="16" cols="80"></textarea></form>`, and then try to type - and = in it. If you take this on, it would be great of any keyboard events that trigger actions in book reader only do so if the book reader element or its children have focus. If not, all key* events should continue to bubble up.

**Comment by Kaku-g** [comment]
hey @cdrini  i would like to work on this issue.Where can I locate the searchbox file?

**Comment by nikhilgupta2001** [comment]
hey @cdrini is this still open?  i would like to solve it

**Comment by cdrini** [comment]
It looks like the issue on IA is because the search input is inside a web components. Run this in the console to reproduce:

```js
customElements.define('test-element', class extends HTMLElement {
  constructor() {
    // Always call super first in constructor
    super();

    // Element functionality written in here

    this.attachShadow({mode: 'open'});
    this.shadowRoot.append(document.createElement('input'));
  }
});
$(document.body).append($(`<test-element/>`));
```
