### ISSUE TITLE
Move ./BookReaderDemo/index.html to ./index.html

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#387]
Netlify urls display a 404 because we don't have an HTML file at the root; let's just move the demo file to be at the root of the project.

## Summary of Requirements
- [ ] Move ./BookReaderDemo/index.html to ./index.html
- [ ] Update all references inside `index.html` to point to the correct files
- [ ] Update any references to `./BookReadederDemo/index.html` to point to the new index.html

**Comment by anirbansaha782** [comment]
i want to take this issue

**Comment by shaneriley** [comment]
@anirbansaha782 It's all yours! This will make it much easier to pass along review app URLs.

**Comment by ForgottenProgramme** [comment]
@shaneriley , Is the issue still open? 
Can I take it up?
