### ISSUE TITLE
Fullscreen bug on this item

### ISSUE THREAD

**Issue by rchrd2** [internetarchive/bookreader#395]
There is a bug with full screen on the following item. It may be an issue with all items with multiple sub items (I have not tested).

https://archive.org/details/1619project/page/n15/mode/2up

<img width="1547" alt="Screen Shot 2020-07-26 at 9 58 22 PM" src="https://user-images.githubusercontent.com/182479/88505040-29fbe800-cf8b-11ea-8901-89389f899a61.png">

To reproduce:
- Visit the item linked above. 
- Enter full screen
- The full screen mode is not taking up the whole browser window, like it should.

**Comment by shaneriley** [comment]
Note: issue is only present in Safari. Chrome, Firefox, and Edge function as expected.

**Comment by shaneriley** [comment]
Fixed with latest deployment.
