### ISSUE TITLE
jQuery version incompatibility

### ISSUE THREAD

**Issue by scannermobs** [internetarchive/bookreader#40]
Any plans to get the plugin working with recent versions of the dependencies (primarily jQuery itself)? I've been unable to get it working on 1.11.x and am currently on 1.4.2, which is undesirable.

N.B. For others, incompatible jQuery version (even with migrate) results in a 'partially-loaded' plugin, which does not perform core actions such as display the book content.

**Comment by eduh** [comment]
I do use jQuery version 1.4.3 which is not vulnerable to certain bugs. Not an ideal situation but it works. Looks like active development on the bookreader is at a very low level.

**Comment by eduh** [comment]
Perhaps this is interesting.  These guys did patched it :  https://bitbucket.org/nlireland/multipage_image_viewer/src/7ec26c4cc6025d7e9e3a99d2f829bcc2dcfde1ca/app/assets/javascript/?at=master  But they are also switching to diva.js reader whicxh is more up to date https://ddmal.github.io/diva.js/

**Comment by nikolas** [comment]
I have a PR to get it to at least 1.5.2 here: #41. Can someone merge it? @rajbot ?

**Comment by rchrd2** [comment]
BookReader now works with 1.10.x.
