### ISSUE TITLE
Bookreader image requests return 404

### ISSUE THREAD

**Issue by benwbrum** [internetarchive/bookreader#410]
**Description**

Three days ago, the Bookreader client embedded within [FromThePage](https://github.com/benwbrum/fromthepage) started receiving `404` error codes from the Internet Archive when attempting to display images which had previously worked.  At the time, this seemed to be the same problem as the `417` error returned by the BookURL `download` API when requesting thumbnails, however that problem has sense been resolved, while Bookreader requests receive `404`.  This renders image display unusable. 

**Evidence / Screenshot (if possible)**

A live example of this problem can be seen at https://fromthepage.com/benwbrum/jeremiah-white-graves-diaries/jeremiah-white-graves-diary-volume-2-book-10/display/504359

When viewing the Javascript console, Bookreader is requesting this URL:
https://ia600500.us.archive.org/BookReader/BookReaderImages.php?zip=%2F26%2Fitems%2FJeremiah_White_Graves_Diary_Volume_2_Book_10%2FJeremiah_White_Graves_Diary_Volume_2_Book_10_jp2.zip&file=Jeremiah_White_Graves_Diary_Volume_2_Book_10_jp2%2FJeremiah_White_Graves_Diary_Volume_2_Book_10_0000.jp2&scale=4.0588235294117645&rotate=0

It is receiving a `404` from the server.

For reference, Bookreader is configured as follows when FromThePage renders the containing page HTML:

```javascript
br.bookId        = "Jeremiah_White_Graves_Diary_Volume_2_Book_10";
br.zip           = "/26/items/Jeremiah_White_Graves_Diary_Volume_2_Book_10/Jeremiah_White_Graves_Diary_Volume_2_Book_10_jp2.zip";
br.subPrefix     = "Jeremiah_White_Graves_Diary_Volume_2_Book_10";
br.server        = "ia800500.us.archive.org";
br.bookTitle     = "Diary of Jeremiah White Graves, Volume 2, Book 10";
br.bookPath      = "/26/items/Jeremiah_White_Graves_Diary_Volume_2_Book_10";
br.bookUrl       = "https://www.archive.org/details/Jeremiah_White_Graves_Diary_Volume_2_Book_10";
br.imageFormat   = "jp2";
br.archiveFormat = "zip";

br.pageW         = [1724];
br.pageH         = [2691];
br.leafMap       = [0];
br.pageNums      = [''];
br.numLeafs      = br.pageW.length;
br.pageTitle     = "July 18, 1855 - August 5, 1855";
```

**Expectation**

The server should return the image to Bookreader, as it did prior to this week.

**Context**

This does not seem to be browser-specific; it has occurred for me on Chrome in Windows and Linux, but has been reported by customers and all users who have tried it.

**Stakeholders**

Since COVID-19 sent their field workers home, staff at the United States Department of Agriculture have been continuing to work remotely by transcribing material at the National Agriculture Library hosted on the Internet Archive, using the transcription tool FromThePage.  This problem is stopping staff members from being able to work remotely, so the USDA is inquiring about this regularly.
@saracarl

**Comment by iisa** [comment]
Hi @benwbrum and @saracarl,


Thanks for reaching out and our apologies for the disruption. We were unaware that anyone else was hitting our internal link to images directly.
 
We are currently in development to bolster our image infrastructure and our internal links will be in flux. In order to provide the best service that we can, it is best to point to our images using our public endpoint: `https://archive.org/download/<identifier>/page/<N>`

Our image/book url docs are here: https://openlibrary.org/dev/docs/bookurls for more details.
 
---
With the example above, you can actually get to the page like this:
 
https://archive.org/download/Jeremiah_White_Graves_Diary_Volume_2_Book_10/page/leaf0

So, in pseudocode, `<N> = “leaf” + br.leafMap`
You may also access the page with `br.pageNums` value above, do confer with the docs to get the proper syntax.

Hope that helps, let us know if you have more questions.

**Comment by saracarl** [comment]
Thanks, we’ll try that. 

We suspect the reason we used the internal URLs was because this integration was written in 2010!

**Comment by benwbrum** [comment]
Many thanks for your help on this!  

We've [switched our code](https://github.com/benwbrum/fromthepage/pull/1956) over to use Open Seadragon and IIIF for displaying Internet Archive-hosted images, so believe we have fixed the problem.  Bookreader has served us well for a decade, but OSD is the same image client we use for all other integrations, so removing it was a long-delayed goal for our project.

Thanks to the Bookreader team for a decade of helping people--especially naturalists working on natural history collections--transcribe documents!
