### ISSUE TITLE
Desktop BR width: < 790px missing zoom buttons in menu

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#411]
**Description**

Neither the side menu nor the bottom bar have ways to zoom/unzoom. In the side menu the DOM elements exists.

In one sets `zoom_in` to `width: 20px; height: 20px; background-color: #000` it seems to render a clickable, working zoom button area.

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

![archive org_details_shorthistoryofne0000brys_u9b9_page_93_mode_1up_admin=1 q=book (4)](https://user-images.githubusercontent.com/978325/89616540-6c4fdf80-d83d-11ea-858d-d8b46f7cce28.png)
![archive org_details_shorthistoryofne0000brys_u9b9_page_93_mode_1up_admin=1 q=book (2)](https://user-images.githubusercontent.com/978325/89616553-71ad2a00-d83d-11ea-92e7-e9d6ac153c1b.png)

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?

Ideally, zoom buttons always show up (they are currently buried 2 levels deep in menus. Ideally, ideally, there would be pinch-to-zoom, but I digress. At bare minimum, the zoom buttons should render correctly in the side menu

**Context**

> What operating system? What browser type and version?

Linux, chrome

**Proposal & Constraints**
**Stakeholders**

> @-tag any stakeholders of this bug

Suggesting high priority only because the book becomes unusable if zoom required in this position. Not urgent as most folks likely don't even know this hidden zoom feature exists.

@shaneriley , @iisa , @jbuckner , @cdrini

**Comment by cdrini** [comment]
This contains the old version; I'm still getting the zoom buttons disappearing around there (I think that's always been the case): https://www-drini.archive.org/details/goody

The zoom buttons missing from the mmenu is a regression though.

**Comment by iisa** [comment]
circling @pezvi here

**Comment by shaneriley** [comment]
Per Jim Shelton, the mobile zoom buttons and heading are to be removed. The branch https://github.com/internetarchive/bookreader/tree/new-chrome-adjustments removes them completely and renders the zoom in/out buttons until mobile instead of until tablet.
