### ISSUE TITLE
Add "space-after-keywords" always eslint + fix violators

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#445]
Eslint docs: https://eslint.org/docs/rules/space-after-keywords

### Summary of Requirements
- [ ] New rule added to eslint rc
- [ ] `npm run lint:fix` used to fix any violators

### Stakeholders

**Comment by nikhilgupta2001** [comment]
@cdrini  
Hey! i would like to work on this

**Comment by Abhirup-99** [comment]
Hi @cdrini I would like to work on this.

**Comment by Yashs911** [comment]
@cdrini Please have a look at my PR and suggest any changes I need to make.
