### ISSUE TITLE
Add "space-before-blocks" always eslint and fix violators

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#470]
Eslint docs: https://eslint.org/docs/rules/space-before-blocks

### Summary of Requirements
- [ ] New rule added to eslint rc
- [ ] `npm run lint:fix` used to fix any violators

### Stakeholders

@Yashs911

**Comment by cdrini** [comment]
@Yashs911 Would you be interested in taking this one?

**Comment by Yashs911** [comment]
@cdrini Yes

**Comment by cdrini** [comment]
Awesome! I'm assigning it to you :)

**Comment by Yashs911** [comment]
@cdrini PR created.
