### ISSUE TITLE
Remove menu tab at the bottom right

### ISSUE THREAD

**Issue by iisa** [internetarchive/bookreader#487]
- Remove menu tab at bottom right of screen, just above the 'fullscreen' button
![image](https://user-images.githubusercontent.com/7840857/94995398-de4d5800-0552-11eb-9b33-7d51f052aa25.png)

Acceptance: 
- dom element is removed
- css for that button is removed

When PR:
- add a gif to show that on-page-load, the tab is no longer present

**Comment by Yashs911** [comment]
Hi, @iisa I would like to work on this issue.

**Comment by Kunal-2001** [comment]
Hey @iisa I am new to this project. If anyone is not assigned can i work on this issue ?

**Comment by kaiwalyakoparkar** [comment]
Hi, @iisa I would like to work on this issue, Would you please guide me.

**Comment by Yashs911** [comment]
Hi, @Kunal-2001 PR #488 already fixed this issue.

**Comment by Yashs911** [comment]
@iisa I guess we can close this issue and I was wondering how can I connect with bookreader mentor for GSoC 2021. I tried mailing but the email address was not found.

**Comment by cdrini** [comment]
Closed by #488
