### ISSUE TITLE
Failed search results text not rendering <br>

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#505]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

Failed search results text not rendering `<br>`

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

![archive org_details_whole_earth_review_75_page_n115_mode_1up_q=Mark+Carranza](https://user-images.githubusercontent.com/978325/97098855-1a9a4280-163f-11eb-9040-b4b73326c59b.png)

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?

**Context**

> What operating system? What browser type and version?

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by ArunTeltia** [comment]
Can I work on this issue?
