### ISSUE TITLE
Text Speed selector has white text on white on Chrome

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#507]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

**Evidence / Screenshot (if possible)**

![image](https://user-images.githubusercontent.com/6251786/97233294-20b22f80-17b5-11eb-86d7-2cef269091f4.png)

> Include evidence of the problem or provide a screenshot.

**Expectation**

The text should be black inside the dropdown.

**Context**

Chrome 86 @ Win10

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**

@iisa

**Comment by participator** [comment]
PR #511 added to fix UI issue
