### ISSUE TITLE
Back/forward SVG icons should have font-family: sans-serif

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#508]
The icons should have `font-family: sans-serif` set in their SVG files on the `<text>` elements.

**Evidence / Screenshot (if possible)**
![image](https://user-images.githubusercontent.com/6251786/97233557-87cfe400-17b5-11eb-8bcb-1e5772601be5.png)

**Context**

Tested on FF82 @ Win10

**Stakeholders**

**Comment by mkamranhamid** [comment]
Is it still available?
