### ISSUE TITLE
Table of contents has black text on black

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#514]
To reproduce:

1. Go to https://lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive.html?ocaid=adventuresofoli00dick#page/n15/mode/1up
2. Resize window until hamburger icon appears
3. Open the table of contents

**Evidence / Screenshot (if possible)**
![image](https://user-images.githubusercontent.com/6251786/97435062-5579d000-18f6-11eb-9792-d599abeccfc3.png)

**Stakeholders**

@Pyrojet99 @shaneriley

**Comment by xhalin01** [comment]
Hello, I want to solve this issue.

**Comment by ArunTeltia** [comment]
@xhalin01 I am sorry about my pull request I did not see the message during my pull request I will close my issue
