### ISSUE TITLE
When using mobile phones, zoom buttons show up only in landscape mode

### ISSUE THREAD

**Issue by senthils-aukbc** [internetarchive/bookreader#529]
I am developing a website at:

https://katha-jharna-hindi.netlify.app/

If I go to any of the story links in a cellphone, the zoom magnifying glass buttons at the bottom right don't show up when in portrait mode. They appear if the phone is changed to landscape mode.
It does not seems to be due to a lack of space. If I remove the toggles for one page and two page mode also the behavior persists.
Is this the desired behavior or a bug ?

**Comment by Dnouv** [comment]
@senthils-aukbc, thanks for opening this issue; it seems that this is the desired behavior since, in portrait mode, there is limited space as compared to landscape mode, so the zoom option does not show up.

**Comment by cdrini** [comment]
The zoom buttons have since been removed in favour of pinch zoom
