### ISSUE TITLE
Bookreader breaks when initialized by URL in "_autoReadAloud=show" mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#578]
## Description

Open Library offers both a 1st class Read/Borrow & Listen button options for initiating their reading experience in Bookreader.

A recent change to Bookreader has possibly introduced a regression which breaks the Bookreader's ability to start or stop audio when the `_autoReadAloud=show` GET query parameter is present.

## How to repro:

url https://archive.org/stream/crucialconversat00patt?ref=ol&_autoReadAloud=show

## Priority

I wouldn't necessarily call this a "drop everything P0" but I think a lot of people would be grateful if this were solved this upcoming week. The experience for a patron who clicks the "Listen" button is that the Bookreader has no way of repairing its state (i.e. refreshing, clicking the headphones button to deactivate/re-activate the feature does not fix the problem). The Listen button does get used fairly frequently according to our analytics.

Once in the broken state (anyone who clicks the Listen button on Open Library), it seems the only way [I've been able to find] to recover from the issue is to remove the `_autoReadAloud=show` option from the get parameters and then refresh

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

![archive org_stream_kiterunne00hoss_ref=ol _autoReadAloud=show admin=1 (1)](https://user-images.githubusercontent.com/978325/102730935-2f1b5400-42eb-11eb-890a-5afcf27959e8.png)
![archive org_stream_kiterunne00hoss_ref=ol _autoReadAloud=show admin=1](https://user-images.githubusercontent.com/978325/102730936-304c8100-42eb-11eb-895e-e33fc2e2f5b0.png)

*Context**

> What operating system? What browser type and version?

Multiple platforms affected? Linux desktop + Chrome & Android + chrome

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

I know @cdrini will be out this week @iisa, @bfalling  is this something that you can spend a moment taking a look at early this coming week

**Stakeholders**

> @-tag any stakeholders of this bug

@bfalling @iisa @cdrini

**Comment by ishank-dev** [comment]
Hi, @mekarpeles 
I did a small element inspection and looks like its a small CSS issue, when the `` _autoReadAloud=show `` in the query parameters is present, the class assigned to the BRcontrols is ``read-aloud`` with the ``block`` style, while when we click on read-aloud button i.e when the `` _autoReadAloud=show `` is not present then the class assigned to BR controls is ``read-aloud visible`` which has the ``flex`` style. Attaching screenshots for better understanding.
#### Case when `` _autoReadAloud=show `` is present in the query
![Screenshot_20201222_130441](https://user-images.githubusercontent.com/45262592/102862006-770aba00-4456-11eb-9072-ccf1f1eec97e.png)
#### Case when `` _autoReadAloud=show `` is not present in the query
![Screenshot_20201222_125621](https://user-images.githubusercontent.com/45262592/102861994-740fc980-4456-11eb-888c-949042e0be3f.png)

I think simply adding the class ``visible`` in the previous case would fix it. OR we can change the display property to ``flex`` in the first case, as per the convenience
This should work in both stream and details mode.

**Comment by iisa** [comment]
released on archive.org
