### ISSUE TITLE
Experimental Option High Contrast only available in mobile view

### ISSUE THREAD

**Issue by html5cat** [internetarchive/bookreader#63]
There doesn't seem to be a way to toggle `Experimental (may not work)` options in desktop view – it's only available via hamburger menu.

**Comment by rchrd2** [comment]
Yes this is true. Do you have an idea where this could fit into the desktop UI?

**Comment by mekarpeles** [comment]
Next to the "speaker" icon maybe? Or next to the +/- magnifying glass?

**Comment by rchrd2** [comment]
I think there probably needs to be a place for more advanced settings. There have also been requests for the autoplay feature.

Maybe if there was a cog icon, which opened up a modal with more advanced controls. This could also house other things, like text-to-speech voice settings.

**Comment by LeadSongDog** [comment]
Some settings that would make sense:
1. monochrome
2. invert (a.k.a. night or powersave mode)
3. fill-window (autozoom)
4. default 1-up/2-up/grid
5. default scroll/page

**Comment by mekarpeles** [comment]
I think the text-to-speech setting should always show and never be hidden within a menu.

**Comment by cdrini** [comment]
The UIs are now consistent across desktop and mobile
