### ISSUE TITLE
One-page view last page number display

### ISSUE THREAD

**Issue by Kunal-2001** [internetarchive/bookreader#648]
**Description**

On One-page view the last page does not show correct page number

**Evidence / Screenshot (if possible)**

![Internet_Archive_Bug_1](https://user-images.githubusercontent.com/61347506/110541184-69a7c680-814d-11eb-96e5-5fe7e94732d5.png)

**Expectation**

For the above screenshot page number 5 should display

**Context**

Operating System: Ubuntu 20.04

**Proposal & Constraints**

 The app should check if the state is in One-page view then it should allow page number limit upto the total number of pages

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by git-anurag-hub** [comment]
Working on this.

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on this?

**Comment by git-anurag-hub** [comment]
@Priyaraj17 I was busy on some other issues. Working on this now. :)
