### ISSUE TITLE
Read Aloud & Magnify options buried on mobile

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/bookreader#65]
On mobile devices, users are even more likely (because of limited real estate) to want to invoke the read aloud option and or magnification setting.

re: read aloud -- Suggesting that either (a) it appears on the main UI or (b) its behavior changes so when you click it on mobile, instead of nesting/opening a second menu which says "Read Aloud" that this should be a button which just starts/stops the reader.

I might suggest just shrinking the book title and putting the +/- and read aloud on the upper right of the top-bar

**Comment by waleedj99** [comment]
Hi, i have made a pull request resolving this issue 
#178

**Comment by cdrini** [comment]
Mobile now has pinch zoom, and readaloud is in the mobile menu.
