### ISSUE TITLE
GSOC Guidance

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [internetarchive/bookreader#655]
Hello, I am Kaiwalya Koparkar, I have never contributed before to the internet archive. But, I really want to get involved in such an amazing community. I would like to do the contribution not just for GSOC but for a lifetime and make good books available to their desperate readers. I am front - end developer getting my hand dirty in the newest technology trends. I would like to enhance the UI/UX of the website and make it more convincing to the readers. I think GSOC has given me an opportunity to get involved with the internet archive. Could you please guide me?

**Comment by crew-guy** [comment]
Hey Kaiwalya,
It's great to hear your passion for open source. I'm glad you share the collaborative feeling. 
Go through these links to start contributing.
[Open Source GitHub Tutorial](https://www.youtube.com/watch?v=3HqN-YS8eso)
[Orientation](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md)
[Local development environment](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md)

**Comment by kaiwalyakoparkar** [comment]
Thank you @crew-guy, I would surely go through these links and start contributing as soon as possible. And if I face any issue I will get back to you.

**Comment by Adityakushwaha142** [comment]
Heyy everybody !! My name is Aditya . I am a FullStack MERN Developer . I am Excited to contribute in internet archive . One thing i want to know is there any chat channel in internet archive organisation

**Comment by cdrini** [comment]
Best path is to try to find good first issues. internetarchive/openlibrary has a big contributor base!
