### ISSUE TITLE
GSOC 2021 - interaction with mentors

### ISSUE THREAD

**Issue by Ankit27Agg** [internetarchive/bookreader#657]
Hi there,

My name is Ankit Aggarwal. I'm new here and i want to contribute to this project.
I am eager to find a new opportunity through gsoc to enhance my skills so that i can contribute more to such amazing open source projects.
I want the mentors to please guide me in this project like how to get started?

Thanks
Have a nice day😊.

**Comment by SwapnilSoni1999** [comment]
Read their contributing guide and follow steps to setup env.
Once you get the project up and working. Start commiting and contribute to this project.

**Comment by cdrini** [comment]
Hi the normal proposal guidelines apply: https://google.github.io/gsocguides/student/writing-a-proposal . If there are any special things we're looking for for a specific gsoc, we'll comment !
