### ISSUE TITLE
Changing var to const or let.

### ISSUE THREAD

**Issue by Priyaraj17** [internetarchive/bookreader#674]
I was thinking of changing the var declarations to either const or let as it is the modern-day ES6 syntax. 

I would like to work on this.

**Comment by shivambhatia5432** [comment]
I would like to take up this issue

**Comment by Priyaraj17** [comment]
@shivambhatia5432 actually brother I am working on it. Can you take some other issue?

**Comment by shivambhatia5432** [comment]
No issues 😄

**Comment by cdrini** [comment]
Hi! The codebase already uses `const`/`let` ; I opened a new issue for the one file that needs it here: #937
