### ISSUE TITLE
GSoC Proposal 2021.

### ISSUE THREAD

**Issue by crew-guy** [internetarchive/bookreader#703]
**Respected Recipient,**

I am Ankit Sanghvi, a 19 year old **full stack developer** from India. I have been programming in this domain for over a year now and wish to contribute back to the community.  🚀

I have been an avid user of this amazing software and have really learnt a lot not only from the books I borrowed, but from your constant **relentlessness** to make education and information available to all in the most convenient format possible. Hence, I really wish to use my skills to contribute to this noble cause that is spearheading the very fundamentals of "**free education for all**" 📖

I have familiarized myself in detail with the codebase, design patterns, libraries, frameworks and all the supporting documents and have quite a deep understanding of most of the logic in the iaux and bookreader repositories. I have raised some PRs and issues as well. ([Issue #1](https://github.com/internetarchive/iaux/issues/536), [PR #1](https://github.com/internetarchive/iaux/pull/540), [PR #2](https://github.com/internetarchive/iaux/pull/541)). I have even brought together a small community all on my own ([source issue](https://github.com/internetarchive/iaux/issues/543)) and have even gone **out of my way** to teach myself concepts about Storybooks and Lite Elements to just start contributing.

I know do realise that you're a really busy team but honestly, pursuing my love for software development, I am currently a 1000 miles away from home and family, at an internship, currently suffering from COVID 19 and have a hard time managing the team and this all with my academics and yet I am prepared to **stand firm in my dedication** towards contributing to the same motive that you all carry. I really feel I can **make this work**. 

I would truly like to **know the team** better and be part of your conversations, idea **brainstorming** sessions and discussions and hence, I request you to invite me to your **Slack channel** and **mailing list** for a better collaboration experience.

Also, being from a not-so-financially-strong background, I cannot thank you all enough for helping me learn from your **massive archive of knowledge** for free all this while. I have been following the Internet Archive for quite some time and the amount of work you all put in, be it digitization and indexing of books, or workshops or a constantly evolving software, is a **motivational celebration of education**. You all are doing something truly **inspirational** and it would be an honor to work towards such a fulfilling cause alongside a group of such brilliant and selfless people.

I am sharing my [Resume](https://drive.google.com/file/d/1ARFQVmFfM25khTGj1pFhmxlnPHRA_uuj/view?usp=sharing) and [GSoC proposal](https://docs.google.com/document/d/1e_X2cjh61Hzmfbdz6omAS0XIs09-Asjevgxb7MlbiAQ/edit?usp=sharing) for your perusal.

All I ask is give me **one shot** at this. I will really pour my heart and soul into this, right from development to team management and code review. I promise I won't let you down.

I really **look forward** to working with you !

**Stakeholders**
@iisa @jbuckner @mitra42

**Comment by mekarpeles** [comment]
Hi @crew-guy, thank you for your sincere message and for investing time to create a proposal and reach out. First and foremost, reading your message, I hope you recover to full health quickly and take the necessary time to feel better. I can tell how much you care and also how much you are contending with in order to make this work. We're reviewing your proposal and I am happy to discuss with you further over email to ensure you have access to all the channels you need.

You may reach me at mek@archive.org.

**Comment by crew-guy** [comment]
Wow !! I am legit smiling right now !! I can't explain how much this means  to me ! 😄

**Comment by mekarpeles** [comment]
Resolved in https://github.com/internetarchive/iaux/issues/543
