### ISSUE TITLE
Search inside borrowed books

### ISSUE THREAD

**Issue by fenopa** [internetarchive/bookreader#788]
Hi, full text search inside borrowed books doesn't seem to work properly ever.

Whenever I find a book while searching something and then borrow the book and try to find things I was looking by doing a search inside, it just stucks loading indefinitely, very frustrating.

**Comment by iisa** [comment]
hi @fenopa , thanks for checking in.  let's get to the bottom of your issue.  please can you tell us:

- book you are reading & what you searched
- your computer operating system
- which browsers did you use?
- did you find the book during a search on archive.org?

**Comment by fenopa** [comment]
Hi, thank you for response

- I feel like it's related to books having too many pages

Any search on this stucks loading indefinitely for example: https://archive.org/details/bowkerscompletev0001unse_u7e2
Try to search "Christmas" for example

This gives "Sorry, there was an error with your search. Please try again." error instantly with any search for example while others generally just stuck with loading indefinitely
https://archive.org/details/whoswhoinamerica10marq

This stucks indefinitely as well: https://archive.org/details/performerstelevi0002inma

Just some examples

- Windows 10
- I generally use Firefox, latest stable version always
- Yes, generally find them via Archive.org's "Search text contents" feature, but sometimes via Google as well

Thank you so much.

**Comment by iisa** [comment]
oh yes, I see what you're saying.  I have reproduced your error, and it looks like something is amiss with the service.  I will escalate up to the search team.  In the meantime, we _just_ added the ability for folks to cancel the search-in-progress.

did you see these cancel buttons (inside left panel, top right of on-book progress popup)?  you can use those to get out of a search-in-progress
<img width="589" alt="image" src="https://user-images.githubusercontent.com/7840857/120671664-771bd680-c446-11eb-82e7-714ef9b6dbbc.png">

**Comment by fenopa** [comment]
> did you see these cancel buttons (inside left panel, top right of on-book progress popup)? you can use those to get out of a search-in-progress
yeah sure, it's helpful but being able to make a search would be more helpful :)

Thank you for your care and forwarding it to the search team, hope it's not too hard to fix, did they say anything about it?

cheers

**Comment by gumbol** [comment]
hello i have developed a [vanilla js code](https://github.com/gumbol/count-words) for counting the occurance of a word or phrase in a string. I am not sure what features the ia requires in the search function. but if this looks good to maintainers it could be extended easier than jquery code.

**Comment by cdrini** [comment]
The provided examples now work correctly! e.g  https://archive.org/details/bowkerscompletev0001unse_u7e2/mode/2up?q=Christmas
