### ISSUE TITLE
Add eslint-plugin-no-jquery to highlight/autofix deprecated jquery

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#842]
This plugin can auto-fix a number of deprecated jquery calls; helping open the path for us switching to jquery 3, or dropping jquery altogether.

See https://www.npmjs.com/package/eslint-plugin-no-jquery .

See this PR for how it was added to open library: https://github.com/internetarchive/openlibrary/pull/5201/files

**Comment by soham4abc** [comment]
I am willing to work on this issue. If possible pls do assign.
