### ISSUE TITLE
autoplay not working for the "tabbed-audio-player"

### ISSUE THREAD

**Issue by waldenn** [internetarchive/bookreader#856]
**Description**

The "tabbed-audio-player" (the audio-player showing cover art, Spotify links, etc.) does not auto-play the audio, when the "autoplay=1" parameter is added to its URL.

Examples:
- https://archive.org/details/lp_cantata-no-117-cantata-no-93_johann-sebastian-bach-frankfurter-kantaten&autoplay=1
-  https://archive.org/details/lp_voices-of-the-night-songs-duets-and-ensemb_the-songmakers-almanac-brahms-schumann&autoplay=1

> What should be happening?

Auto-play through the list of audio-files of this item, just like is done for the non-tabbed-audio-player items.

Thanks!

**Comment by cdrini** [comment]
Hey thanks @waldenn ! I'm going to close this here since this is an issue with the audio player, if I'm understanding correctly.

@iisa @traceypooh could you transfer this to the right repo if one exists?
