### ISSUE TITLE
Click-and-drag no longer working in two-page view

### ISSUE THREAD

**Issue by Mister-Steak** [internetarchive/bookreader#881]
In "to borrow" books, the click-and-drag method of scrolling doesn't work, though it still works as before in Open Library books. It also still works in one-page view.

When holding down the mouse button and dragging, nothing happens at all. However, when dragging toward the very top or bottom of the display it'll scroll in that direction as if highlighting text, though no text appears to highlight when I do this. Also, I tested this on pages with no text and the effect was the same. When dragged off the reader, text on the website will highlight, which is not the case for Open Library books. When releasing the mouse, the page turns toward the side of the book the pointer was on when first pressed, even when the pointer is no longer on the book.

~~edit: When a "to borrow" book is zoomed out enough to not require scrolling, text on the website (sometimes?) no longer highlights when dragging off the reader, and (sometimes?) the page no longer turns when releasing after a click-and-drag. Needs more investigation into that edge case.~~ I'm failing to replicate this, but it seemed to happen once.

edit 2: It appears that switching to one-page view after attempting any click-and-drag action in two-page view will cause scrolling to break in one-page view as well until the webpage is refreshed. This also happens if you've previously switched from one-page to two-page view, regardless of click-and-drag behavior.

I tested this in Chrome and Firefox with multiple "to borrow" books, as well as Open Library books. It doesn't matter whether the book has been borrowed yet or not, nor does fullscreen mode. The last time I used archive.org's bookreader was a number of months ago, so I'm not sure when this issue might have been caused.
(the edits were only tested in Firefox with the first linked book)

The "to borrow" books I tested were:
https://archive.org/details/ourorientalheritage00dura/   (where I originally noticed the issue)
https://archive.org/details/harrypottergoble0004rowl/
https://archive.org/details/it0000king/

The Open Library books I tested (where it works fine) were:
https://archive.org/details/librodebuenamort00ruiz/
https://archive.org/details/worksofgeorgemer35mereuoft/
https://archive.org/details/elingeniosohidal02cerv_4/

I made a github account just to say this. I hope I'm using it right.

**Comment by khareyash05** [comment]
Hi @cdrini I would like to work on this issue . Could you please help me set up the dev environment so that I can reproduce the same on my local machine
