### ISSUE TITLE
Replace vars with const/let in src/BookReader.js

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#937]
In working towards modernizing the BookReader JavaScript, we want to switch to using `const`/`let` (see [here](https://github.com/internetarchive/bookreader/wiki/JS-Modernization-Plan-Notes#uses-constlet-instead-of-var) for why).

Summary of Requirements:

* [ ] Remove the `BookReader.js` override in `.eslintrc.js` that allows `var`
* [ ] There are no occurrences of `var` in `src/BookReader.js`
    * You might try running `npx eslint --fix src/BookReader.js` after removing the override. That might fix everything automagically!
* [ ] `const` is preferred over `let` where possible

**Comment by sancodes** [comment]
I would like to help on this.Let me know if its still open

**Comment by Aadilhassan** [comment]
I have created a pull request for that.

**Comment by cdrini** [comment]
Thanks folks! Since you asked first, do you want to take a stab at it @sancodes ?

**Comment by sancodes** [comment]
yes, @cdrini. I will be glad to take the assignment.

**Comment by sancodes** [comment]
Hello, @cdrini, I have completed the task, please take a look and aware me if I need to change or fix anything regarding this task. 
Thanks.

**Comment by sancodes** [comment]
Hello @cdrini can you help me understand the first task? 
-  Remove the BookReader.js override in .eslintrc.js that allows var

when you say remove the BoookReader.js 'override' in .eslintrc.js, what do you mean by that?

**Comment by cdrini** [comment]
Sure! So eslint is configured by this file: https://github.com/internetarchive/bookreader/blob/master/.eslintrc.js

In there we block all files from having `var` in them. If someone was to add `var` to one of our .js files, eslint would throw an error.

That rule applies to all files _except_ `src/BookReader.js` , because we haven't fixed that yet :)
This section disabled that eslint rule for this file: https://github.com/internetarchive/bookreader/blob/644c0f5b0bdf7bd7c2619624a0bb78eb71dc8ca3/.eslintrc.js#L51-L60

If we remove that section, then eslint will error for every occurrence of `var`. But once it's removed, we can let eslint auto-fix the problem by running `npx eslint --fix src/BookReader.js` .

Does that help?

**Comment by sancodes** [comment]
@cdrini so at the moment, inside that 'overrides', 

rules for 'no-var' is turned off, so that is why `src/BookReader.js` wouldnt complain, if someone were to add 'var'. 

so, ideally it would make sense to just remove the 'overrides' block itself, 
if not, 
we can change inside the `overrides block`
```
"overrides": [ 
   { // TODO; these should be cleaned up as well 
     "files": [ 
       "src/BookReader.js" 
     ], 
     "rules": { 
       "no-var": ["off"], 
     } 
   }, 
 ], 
```
to 
```
"overrides": [ 
   { // TODO; these should be cleaned up as well 
     "files": [ 
       "src/BookReader.js" 
     ], 
     "rules": { 
       "no-var": ["error"], 
     } 
   }, 
 ], 
```
is my understanding correct ? 
then we run the `npx eslint --fix src/BookReader.js`
then check for the possible changes for 'var' to either 'let' or 'const'
and the task should be solved right?

**Comment by sancodes** [comment]
@cdrini, I have finished the task,  please let me know if everything is working fine.
