### ISSUE TITLE
Update to Node 16

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#938]
Node 16 is now LTS, and bookreader is behind other internetarchive packages! So let's update :)

To update, we will need to:
* [x] Change the github workflow files to use Node 16 (eg `.github/workflows/node.js.yml`)
* [x] Locally with Node 16 installed, run `npm install` to update the `package-lock.json` . Commit this.
* [ ] We believe there are some errors in some jest tests with Node 16, regarding unhandled errors inside promises. Run `npx jest` to see if it errors. Try to fix those. If it looks complicated, try to find a way to ignore the errors somehow and open a new issue to fix that separately.

**Comment by kelp-chip** [comment]
Hello! It'll be my first time contributing but could I be assigned this issue?

**Comment by cdrini** [comment]
Go for it, @kelp-chip ! Let us know if you hit any issues

**Comment by kelp-chip** [comment]
Thank you, will do! :)

**Comment by kelp-chip** [comment]
@cdrini, sorry already struggling on the first step. Never touched a .yaml file before, is it as simple as directly changing this 14.x to 16.x [on this line](https://github.com/internetarchive/bookreader/blob/master/.github/workflows/node.js.yml#L20)?

**Comment by cdrini** [comment]
@kelp-chip Yep! That's exactly it. Good sleuthing I forgot about npm-publish.yml!

**Comment by cdrini** [comment]
Hi @kelp-chip ! How's it going? Anything I can help with?

**Comment by cdrini** [comment]
I'm going to un-assign this to give someone else a go in case they're interested :)
