### ISSUE TITLE
Update BookReader to use lit 2.0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#939]
We’re currently using both lit 1 and lit 2, since some of our dependencies use lit 2. Let’s migrate to lit 2.0

Summary of requirements:

* [x] Update installed packages/imports (See https://lit.dev/docs/releases/upgrade/#update-packages-and-import-paths )
* [x] Load polyfill-support file (already done!)
* [x] Other breaking changes   https://lit.dev/docs/releases/upgrade/#adapt-to-minor-breaking-changes
    * [x] `requestUpdate` no longer returns a promise; should await `updateComplete` after calling `requestUpdate`
* [x] https://github.com/internetarchive/iaux-item-navigator/pull/7
* [x] https://github.com/internetarchive/iaux-menu-slider/pull/26
* [x] @cdrini bump version of the above packages in BR

Those seem to be the only changes that affect us, but other things might pop up. Let the migration guide guide you    https://lit.dev/docs/releases/upgrade/

**Comment by Aadilhassan** [comment]
I read all instructions given by lit to migrate to lit 2.0 very carefully, can you assign me for this issue.

**Comment by cdrini** [comment]
Awesome, thank you @Aadilhassan ! I'll take a look at your PR once I'm back on Monday :)

**Comment by Aadilhassan** [comment]
I have made some changes🚀 in my pull request according to the 📔instructions given by you.

**Comment by Aadilhassan** [comment]
### Hello @cdrini 
i need your help  i am getting some  ❌errors in `npm run test` in **build** [https://github.com/internetarchive/bookreader/runs/5221444498?check_suite_focus=true](https://github.com/internetarchive/bookreader/runs/5221444498?check_suite_focus=true)
can you help me with this.
