### ISSUE TITLE
Use Mozilla Common Voice dataset to improve sound quality and add support for more languages

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/bookreader#987]
Currently, the amount of languages is too limited and voices are too robotic.
**Additional Resources**
https://commonvoice.mozilla.org/en/languages

**Comment by cdrini** [comment]
Hi @bicolino34 ! What browser and Operating System are you using? The voices depend a _lot_ on those two factors. For example Chrome and Microsoft Edge have great voice support on Windows. But Firefox on Windows is limited to only system-level voices. There might be ways to add voices to your computer, depending on your Operating System.

**Comment by bicolino34** [comment]
@cdrini I'm using Chrome browser on Windows. So, it's possible to add own voices? How to do it?

**Comment by cdrini** [comment]
These instructions are a little out-dated, but pretty close if you're using Windows 10: https://support.microsoft.com/en-us/topic/download-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130

Here's what the menu looks like for me: 
![image](https://user-images.githubusercontent.com/6251786/157998731-f03fce85-22bc-4e9d-9345-e6107517d277.png) (note the little "Text-to-Speech" icon next to some languages).

But before trying that, I'd recommend giving Microsoft Edge a try. Google Chrome provides 30 languages/voices -- but Microsoft Edge comes with like 104 on my machine :P It even has text-to-speech options which aren't available for installation in the settings menu!
